// ui/components/AgentsSettings.vue
<script setup lang="ts">
import { openUrl } from '../platform';
import ElasticPanel from './ElasticPanel.vue';
import AgentDetails from './AgentDetails.vue';
import AgentDisplaySettings from './AgentDisplaySettings.vue';
import AgentQuotaIcon from '../subscriptions/AgentQuotaIcon.vue';
import { displayMessage } from '../messages';
import { t } from '../i18n';
import { computed, onMounted, ref } from 'vue';
import { NButton, NText, NSwitch } from 'naive-ui';
import { RefreshCw, Settings } from '@lucide/vue';
import { useAgents, agentLinks, name, type Agent } from '../composables/useAgents';
const selectedAgent=ref<Agent>();
const displaySettings=ref(false),settingsOrigin=ref({x:0,y:0,size:28});
function showDisplaySettings(event:MouseEvent){const rect=(event.currentTarget as HTMLElement).getBoundingClientRect();settingsOrigin.value={x:rect.x,y:rect.y,size:rect.width};displaySettings.value=true;}
const detailOrigin=ref({x:0,y:0,size:40});
function showAgent(agent:Agent,event:MouseEvent){const rect=(event.currentTarget as HTMLElement).getBoundingClientRect();detailOrigin.value={x:rect.x,y:rect.y,size:rect.width};selectedAgent.value=agent;}
const { orderedAgents, moveAgent, loaded, loading, saving, error, refresh, toggle } = useAgents();
function adapterFailure(error: string) {
  if (error === 'CLAUDE_ADAPTER_DOWNLOAD_FAILED') return t('agentAdapterDownloadFailed');
  if (error === 'CLAUDE_ADAPTER_CHECKSUM_FAILED') return t('agentAdapterChecksumFailed');
  if (error === 'CLAUDE_ADAPTER_EXTRACT_FAILED') return t('agentAdapterExtractFailed');
  if (error === 'CLAUDE_ADAPTER_PROBE_FAILED') return t('agentAdapterProbeFailed');
  return t('agentAdapterSetupFailed');
}
const props=defineProps<{origin:{x:number;y:number;size:number}}>();
const open=ref(true);



const emit = defineEmits<{ close: [] }>();
const initialAgent: Agent = { agent: 'codex', displayName: 'Codex' };
const visible = computed(() => !loaded.value ? [initialAgent] : orderedAgents.value);
const dragging = ref('');
const dropTarget = ref('');
function dragStart(event: DragEvent, id: string) {
  dragging.value = id;
  if (event.dataTransfer) { event.dataTransfer.effectAllowed = 'move'; event.dataTransfer.setData('text/plain', id); }
}
function finishDrag() { dragging.value = ''; dropTarget.value = ''; }
function drop(id: string) { if (dragging.value) moveAgent(dragging.value, id); finishDrag(); }
function moveWithKey(id: string, direction: number) {
  const index = visible.value.findIndex(agent => agent.agent === id);
  const target = visible.value[index + direction];
  if (target) moveAgent(id, target.agent);
}
onMounted(() => { void refresh(); });
</script>
<template>
  <ElasticPanel :show="open" title="Agents" :origin="props.origin" @close="open=false" @closed="emit('close')">
    <template #title-actions><NButton quaternary circle size="small" :aria-label="t('agentDisplaySettings')" :title="t('agentDisplaySettings')" @click="showDisplaySettings"><template #icon><Settings :size="18"/></template></NButton></template>
    <template #actions><NButton quaternary circle :disabled="loading || !!saving" :aria-label="t('refreshAgents')" :title="t('refreshAgents')" :aria-busy="loading" @click="refresh(true)"><template #icon><RefreshCw :size="20" :class="{spinning:loading}"/></template></NButton></template>
    <div class="agent-grid">
      <article v-for="agent in visible" :key="agent.agent" class="agent-card" :class="{ dragging: dragging===agent.agent, 'drop-target': dropTarget===agent.agent && dragging!==agent.agent }"
        :tabindex="loaded ? 0 : -1" :aria-label="t('reorderAgent', { agent: name(agent) })"
        @keydown.up.self.prevent="moveWithKey(agent.agent,-1)" @keydown.left.self.prevent="moveWithKey(agent.agent,-1)"
        @keydown.down.self.prevent="moveWithKey(agent.agent,1)" @keydown.right.self.prevent="moveWithKey(agent.agent,1)"
        :draggable="loaded" @dragstart="dragStart($event,agent.agent)" @dragend="finishDrag" @dragover.prevent="dropTarget=agent.agent" @drop.prevent="drop(agent.agent)">
          <NSwitch v-if="agent.installed" size="small" class="agent-switch" :id="`agent-${agent.agent}`" :aria-label="t('allowConnectorToUseValue', { agent: name(agent) })" :value="agent.enabled === true"
            :loading="agent.adapter?.state === 'preparing'" :disabled="agent.adapter?.state === 'preparing' || !!saving || loading || typeof agent.enabled !== 'boolean'"
            :title="t('allowConnectorToAcceptRequestsForThisAgent')" @update:value="toggle(agent, $event)" />
        <div class="agent-info">
          <button class="agent-icon" type="button" :aria-label="name(agent)" aria-haspopup="dialog" @click="showAgent(agent,$event)"><AgentQuotaIcon :agent="agent.agent"/></button>
          <span class="agent-copy"><NText v-if="agentLinks[agent.agent]" tag="a" class="agent-name agent-link" :href="agentLinks[agent.agent]" target="_blank" rel="noopener noreferrer" :draggable="false" @click.prevent="openUrl(agentLinks[agent.agent]).catch(cause => error=String(cause))">{{name(agent)}}</NText><span v-else class="agent-name">{{name(agent)}}</span><span v-if="!agent.installed || agent.version" class="agent-version">{{agent.installed ? agent.version : t('agentNotInstalled')}}</span></span>
          <span v-if="agent.installed && agent.adapter && agent.adapter.state !== 'ready'" class="agent-adapter" :role="agent.adapter.state === 'failed' ? 'alert' : 'status'">{{t(agent.adapter.state === 'preparing' ? 'agentAdapterPreparing' : agent.adapter.state === 'failed' ? 'agentAdapterFailed' : 'agentAdapterMissing')}}<span v-if="agent.adapter.error"> {{adapterFailure(agent.adapter.error)}}</span></span>
        </div>
      </article>
    </div>
    <p v-if="error" class="agent-error" role="alert">{{displayMessage(error)}}</p>
  </ElasticPanel>
  <AgentDisplaySettings v-if="displaySettings" :origin="settingsOrigin" @close="displaySettings=false"/>
  <AgentDetails v-if="selectedAgent" :agent="selectedAgent" :origin="detailOrigin" @close="selectedAgent=undefined"/>
</template>

<style scoped>
.spinning{animation:agents-spin 1s linear infinite}
@keyframes agents-spin{to{transform:rotate(360deg)}}
@media(prefers-reduced-motion:reduce){.spinning{animation:none}}

.agent-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:10px;padding:4px 0 12px}
.agent-card{border:1px solid var(--line);border-radius:14px;background:var(--surface);padding:12px;min-width:0;display:grid;grid-template-columns:40px minmax(0,1fr) auto;column-gap:10px;row-gap:4px;align-items:center;align-content:center;transition:border-color 160ms,box-shadow 160ms}
.agent-card[draggable="true"]{cursor:grab}
.agent-card.dragging{opacity:.5}
.agent-card.drop-target{border-color:var(--green);box-shadow:0 0 0 2px var(--green)}
.agent-switch{grid-column:3;grid-row:1}
.agent-card:focus-visible{outline:2px solid var(--green);outline-offset:2px}
.agent-info{display:contents}
.agent-icon{display:flex;width:40px;height:40px;padding:0;border:0;background:transparent;box-shadow:none;cursor:pointer;grid-column:1;grid-row:1 / 3;align-self:center}
.agent-icon :deep(svg){width:100%;height:100%}
.agent-copy{display:contents}
.agent-name{grid-column:2;grid-row:1;min-width:0;font-size:13px;font-weight:500;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.agent-link{text-decoration:none;cursor:pointer}.agent-link:hover{text-decoration:underline;color:var(--green)}
.agent-version{grid-column:2 / 4;grid-row:2;min-width:0;font-size:11px;color:var(--muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
@media(max-width:480px){.agent-grid{grid-template-columns:1fr}}

.agent-adapter{grid-column:2 / 4;grid-row:3;font-size:11px;color:var(--muted);overflow-wrap:anywhere}
.agent-error { color: #a46651; font-size: 12px; padding: 0 0 10px; margin: 0; }
</style>

// ui/components/AgentsSettings.tsx
import { useState } from "react";
import { RefreshCw, Settings } from "lucide-react";
import { t } from "../i18n";
import { openUrl } from "../platform";
import {
  agents,
  orderedAgents,
  moveAgent,
  name,
  agentLinks,
  toggleAgent,
  refreshAgents,
  type Agent,
} from "../state/agents";
import { subscriptions } from "../state/subscriptions";
import { AgentQuotaIcon } from "../subscriptions/QuotaRing";
import QuotaBubble from "../subscriptions/QuotaBubble";
import AgentDisplaySettings from "./AgentDisplaySettings";
import { Dialog, IconButton, Switch, Notice, Loading } from "./ui";
export function AgentDetails({
  agent,
  onClose,
}: {
  agent: Agent;
  onClose: () => void;
}) {
  const { snapshot } = subscriptions.use();
  const provider = snapshot?.settings.enabled
    ? snapshot.providers.find(
        (p) => p.agentId === agent.agent && p.eligible && p.selected,
      )
    : undefined;
  return (
    <Dialog title={name(agent)} onClose={onClose} headerless width={440}>
      <div className="agent-summary">
        <AgentQuotaIcon agent={agent.agent} />
        <div>
          <strong>{name(agent)}</strong>
          <p>{agent.installed ? agent.version : t("agentNotInstalled")}</p>
        </div>
      </div>
      {provider && <QuotaBubble provider={provider} />}
    </Dialog>
  );
}
export default function AgentsSettings({ onClose }: { onClose: () => void }) {
  const state = agents.use(),
    items = orderedAgents();
  const [detail, setDetail] = useState<Agent>(),
    [display, setDisplay] = useState(false),
    [dragging, setDragging] = useState(""),
    [dropTarget, setDropTarget] = useState(""),
    [error, setError] = useState("");
  const canReorder = (agent: Agent) =>
    agent.installed === true && agent.enabled === true;
  function move(id: string, by: number) {
    const list = items.filter(canReorder),
      index = list.findIndex((a) => a.agent === id);
    if (list[index + by]) moveAgent(id, list[index + by]!.agent);
  }
  return (
    <>
      <Dialog
        title="Agents"
        onClose={onClose}
        wide
        actions={
          <>
            <IconButton
              icon={Settings}
              label={t("agentDisplaySettings")}
              onClick={() => setDisplay(true)}
            />
            <IconButton
              icon={RefreshCw}
              label={t("refreshAgents")}
              busy={state.loading}
              disabled={!!state.saving}
              onClick={() => void refreshAgents(true)}
            />
          </>
        }
      >
        {!state.loaded && state.loading && <Loading />}
        <div className="agent-grid">
          {items.map((agent) => (
            <article
              key={agent.agent}
              className={`agent-card ${dragging === agent.agent ? "dragging" : ""} ${dropTarget === agent.agent ? "drop-target" : ""}`}
              tabIndex={canReorder(agent) ? 0 : -1}
              aria-label={
                canReorder(agent)
                  ? t("reorderAgent", { agent: name(agent) })
                  : name(agent)
              }
              draggable={canReorder(agent)}
              onKeyDown={(e) => {
                if (e.target !== e.currentTarget) return;
                if (
                  ["ArrowUp", "ArrowLeft", "ArrowDown", "ArrowRight"].includes(
                    e.key,
                  )
                ) {
                  e.preventDefault();
                  move(
                    agent.agent,
                    ["ArrowUp", "ArrowLeft"].includes(e.key) ? -1 : 1,
                  );
                }
              }}
              onDragStart={(e) => {
                setDragging(agent.agent);
                e.dataTransfer.effectAllowed = "move";
                e.dataTransfer.setData("text/plain", agent.agent);
              }}
              onDragEnd={() => {
                setDragging("");
                setDropTarget("");
              }}
              onDragOver={(e) => {
                if (dragging && canReorder(agent)) {
                  e.preventDefault();
                  setDropTarget(agent.agent);
                }
              }}
              onDrop={(e) => {
                e.preventDefault();
                if (dragging && canReorder(agent))
                  moveAgent(dragging, agent.agent);
                setDragging("");
                setDropTarget("");
              }}
            >
              <button
                type="button"
                className="agent-detail-trigger"
                aria-label={name(agent)}
                aria-haspopup="dialog"
                onClick={() => setDetail(agent)}
              >
                <AgentQuotaIcon agent={agent.agent} />
              </button>
              <div className="agent-copy">
                {agentLinks[agent.agent] ? (
                  <a
                    href={agentLinks[agent.agent]}
                    draggable={false}
                    onClick={(e) => {
                      e.preventDefault();
                      void openUrl(agentLinks[agent.agent]!).catch((e) =>
                        setError(String(e)),
                      );
                    }}
                  >
                    {name(agent)}
                  </a>
                ) : (
                  <strong>{name(agent)}</strong>
                )}
                <span>
                  {agent.installed ? agent.version : t("agentNotInstalled")}
                </span>
              </div>
              {agent.installed && (
                <Switch
                  label={t("allowConnectorToUseValue", { agent: name(agent) })}
                  checked={agent.enabled === true}
                  disabled={
                    !!state.saving ||
                    state.loading ||
                    agent.adapter?.state === "preparing" ||
                    typeof agent.enabled !== "boolean"
                  }
                  onChange={(enabled) => void toggleAgent(agent, enabled)}
                />
              )}
              {agent.installed &&
                agent.adapter &&
                agent.adapter.state !== "ready" && (
                  <p
                    className="agent-adapter"
                    role={agent.adapter.state === "failed" ? "alert" : "status"}
                  >
                    {t(
                      agent.adapter.state === "preparing"
                        ? "agentAdapterPreparing"
                        : agent.adapter.state === "failed"
                          ? "agentAdapterFailed"
                          : "agentAdapterMissing",
                    )}
                    {agent.adapter.error &&
                      ` · ${t({ CLAUDE_ADAPTER_DOWNLOAD_FAILED: "agentAdapterDownloadFailed", CLAUDE_ADAPTER_CHECKSUM_FAILED: "agentAdapterChecksumFailed", CLAUDE_ADAPTER_EXTRACT_FAILED: "agentAdapterExtractFailed", CLAUDE_ADAPTER_PROBE_FAILED: "agentAdapterProbeFailed" }[agent.adapter.error] || "agentAdapterSetupFailed")}`}
                  </p>
                )}
            </article>
          ))}
        </div>
        {(error || state.error) && <Notice>{error || state.error}</Notice>}
      </Dialog>
      {detail && (
        <AgentDetails agent={detail} onClose={() => setDetail(undefined)} />
      )}{" "}
      {display && <AgentDisplaySettings onClose={() => setDisplay(false)} />}
    </>
  );
}
