// ui/components/ElasticPanel.vue
<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, ref, watch } from 'vue';
import { NButton } from 'naive-ui';
import { X } from '@lucide/vue';
import { panelLayers } from '../composables/panels';
import { t } from '../i18n';
const props = withDefaults(defineProps<{ show: boolean; title: string; origin?: { x: number; y: number; size: number; height?: number }; busy?: boolean; headerless?: boolean; width?: number }>(), { width: 800 });
const emit = defineEmits<{ close: []; closed: [] }>();
const panel = ref<HTMLElement>();
const position = ref({ x: 0, y: 0 });
const dragging = ref(false);
let drag: { pointerId: number; x: number; y: number; left: number; top: number } | undefined;
function moveTo(x: number, y: number) {
  if (!panel.value) return;
  const maxX = Math.max(0, (window.innerWidth - panel.value.offsetWidth) / 2 - 20);
  const maxY = Math.max(0, (window.innerHeight - panel.value.offsetHeight) / 2 - 20);
  position.value = { x: Math.max(-maxX, Math.min(maxX, x)), y: Math.max(-maxY, Math.min(maxY, y)) };
}
function startDrag(event: PointerEvent) {
  if (event.button !== 0 || !event.isPrimary || !topmost.value || motions.size || (event.target as Element).closest('.panel-actions')) return;
  const header = event.currentTarget as HTMLElement;
  header.setPointerCapture(event.pointerId);
  drag = { pointerId: event.pointerId, x: event.clientX, y: event.clientY, left: position.value.x, top: position.value.y };
  dragging.value = true;
  event.preventDefault();
}
function moveDrag(event: PointerEvent) {
  if (!drag || event.pointerId !== drag.pointerId) return;
  moveTo(drag.left + event.clientX - drag.x, drag.top + event.clientY - drag.y);
}
function endDrag(event: PointerEvent) {
  if (!drag || event.pointerId !== drag.pointerId) return;
  drag = undefined;
  dragging.value = false;
  const header = event.currentTarget as HTMLElement;
  if (header.hasPointerCapture(event.pointerId)) header.releasePointerCapture(event.pointerId);
}
watch(panel, (node, _, onCleanup) => {
  if (!node) return;
  let height = node.offsetHeight;
  let resizing: Animation | undefined;
  const observer = new ResizeObserver(() => {
    moveTo(position.value.x, position.value.y);
    if (resizing) return;
    const nextHeight = node.offsetHeight;
    const previousHeight = height;
    height = nextHeight;
    if (!props.show || Math.abs(nextHeight - previousHeight) < 1 || window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;
    resizing = node.animate([{ height: `${previousHeight}px` }, { height: `${nextHeight}px` }], {
      duration: 320, easing: 'cubic-bezier(.22,1,.36,1)',
    });
    const animation = resizing;
    void animation.finished.then(() => { if (resizing === animation) resizing = undefined; }, () => {});
  });
  observer.observe(node);
  const constrainPosition = () => moveTo(position.value.x, position.value.y);
  window.addEventListener('resize', constrainPosition);
  onCleanup(() => { observer.disconnect(); resizing?.cancel(); window.removeEventListener('resize', constrainPosition); drag = undefined; dragging.value = false; });
}, { flush: 'post' });
const style = computed(() => ({ '--preferred-width': `${props.width}px`, transform: `translate(${position.value.x}px,${position.value.y}px) scale(1,1)` }));
let layer: HTMLElement | undefined;
let trigger: HTMLElement | undefined;
let origin = { x: 0, y: 0, size: 1, height: 1 };
const topmost = computed(() => panelLayers.value.at(-1) === layer);
function release() { panelLayers.value = panelLayers.value.filter(item => item !== layer); }
function closed() { release(); emit('closed'); void nextTick(() => { if (trigger?.isConnected) trigger.focus({ preventScroll: true }); }); }
const motions = new Map<Element, () => void>();
function cancelTransition(element: Element) { motions.get(element)?.(); }
onBeforeUnmount(() => { release(); motions.forEach(cancel => cancel()); });
function transition(element: Element, done: () => void, opening: boolean) {
  cancelTransition(element);
  if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) { done(); return; }
  const node = element.querySelector<HTMLElement>('.elastic-panel')!;
  const { x, y, size, height: originHeight } = origin;
  const width = Math.max(1, node.offsetWidth), height = Math.max(1, node.offsetHeight);
  const collapsed = {
    transform: `translate(${x + size / 2 - window.innerWidth / 2}px,${y + originHeight / 2 - window.innerHeight / 2}px) scale(${size / width},${originHeight / height})`,
    opacity: 0,
  };
  const expanded = { transform: `translate(${position.value.x}px,${position.value.y}px) scale(1,1)`, opacity: 1 };
  const duration = opening ? 480 : 220;
  node.style.willChange = 'transform, opacity';
  const animation = node.animate(opening ? [collapsed, expanded] : [expanded, collapsed], {
    duration, easing: opening ? 'cubic-bezier(.22,1,.36,1)' : 'cubic-bezier(.4,0,.6,1)', fill: 'both',
  });
  const contentAnimations = Array.from(node.children, child => child.animate(
    opening ? [{ opacity: 0 }, { opacity: 1 }] : [{ opacity: 1 }, { opacity: 0 }],
    { duration: opening ? 280 : 100, delay: opening ? 80 : 0, fill: 'both' },
  ));
  const cleanup = () => {
    motions.delete(element); animation.cancel(); node.style.willChange = '';
    contentAnimations.forEach(item => item.cancel());
  };
  motions.set(element, cleanup);
  void animation.finished.then(() => {
    if (motions.get(element) !== cleanup) return;
    cleanup(); done();
  }, () => {});
}
function enter(element: Element, done: () => void) {
  position.value = { x: 0, y: 0 };
  layer = element as HTMLElement;
  trigger = document.activeElement instanceof HTMLElement ? document.activeElement : undefined;
  const rect = trigger && trigger !== document.body ? trigger.getBoundingClientRect() : undefined;
  origin = props.origin ? { ...props.origin, height: props.origin.height ?? props.origin.size } : rect && rect.width && rect.height
    ? { x: rect.x, y: rect.y, size: rect.width, height: rect.height }
    : { x: window.innerWidth / 2, y: window.innerHeight / 2, size: 1, height: 1 };
  panelLayers.value = [...panelLayers.value, layer];
  transition(element, done, true);
  void nextTick(() => panel.value?.focus());
}
const leave = (element: Element, done: () => void) => transition(element, done, false);
const close = () => { if (props.show && topmost.value && !props.busy) emit('close'); };
// Only our backdrop can dismiss the panel. Browser annotation overlays and
// teleported popovers are outside the panel DOM, but are not backdrop clicks.
let backdropPressed = false;
function isBackdrop(event: MouseEvent) {
  if (event.target !== event.currentTarget) return false;
  const rect = panel.value?.getBoundingClientRect();
  return !!rect && (event.clientX < rect.left || event.clientX > rect.right
    || event.clientY < rect.top || event.clientY > rect.bottom);
}
function backdropDown(event: PointerEvent) { backdropPressed = event.button === 0 && isBackdrop(event); }
function cancelBackdrop() { backdropPressed = false; }
function backdropClick(event: MouseEvent) {
  const dismiss = backdropPressed && isBackdrop(event);
  backdropPressed = false;
  if (dismiss) close();
}
</script>
<template>
  <Teleport defer to=".app-scene">
    <Transition :css="false" appear @enter="enter" @leave="leave" @after-leave="closed" @enter-cancelled="cancelTransition" @leave-cancelled="cancelTransition">
      <div v-if="show" class="panel-layer" :class="{ recessed: !topmost }" :style="{zIndex:55 + Math.max(0,panelLayers.indexOf(layer!)) * 2}" :inert="!topmost" @pointerdown="backdropDown" @pointercancel="cancelBackdrop" @click="backdropClick">
      <section ref="panel" class="elastic-panel" :style="style" tabindex="-1" role="dialog" aria-modal="true" :aria-label="title" @keydown.esc.stop="close">
        <header v-if="!headerless" class="panel-header" :class="{ dragging }" @pointerdown="startDrag" @pointermove="moveDrag" @pointerup="endDrag" @pointercancel="endDrag" @lostpointercapture="endDrag"><div class="panel-title"><h1>{{title}}</h1><span v-if="$slots['title-actions']" class="panel-actions"><slot name="title-actions"/></span></div><div class="panel-actions"><slot name="actions"/><NButton quaternary circle :disabled="busy" :aria-label="t('close')" :title="t('close')" @click="close"><template #icon><X :size="22"/></template></NButton></div></header>
        <div class="panel-content" :class="{headerless, 'with-footer':!!$slots.footer}"><slot/></div>
        <footer v-if="$slots.footer" class="panel-footer"><slot name="footer"/></footer>
      </section>
      </div>
    </Transition>
  </Teleport>
</template>
<style scoped>
.panel-layer{position:fixed;inset:0;display:flex;align-items:center;justify-content:center;padding:20px;box-sizing:border-box}
.panel-layer.recessed .elastic-panel{box-shadow:var(--shadow-recessed)}
.elastic-panel{position:relative;flex-shrink:0;width:min(var(--preferred-width),calc(100vw - 40px));max-height:calc(100dvh - 40px);box-sizing:border-box;z-index:55;background:var(--surface);border:1px solid var(--line);border-radius:28px;box-shadow:var(--shadow-panel);transition:width 320ms cubic-bezier(.22,1,.36,1);display:flex;flex-direction:column;overflow:hidden;outline:none;transform-origin:center;transform:translate(0,0) scale(1,1)}
.panel-header{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:28px 28px 12px;flex-shrink:0}.panel-header h1{font-size:22px;font-weight:600;margin:0}.panel-actions{display:flex;align-items:center;gap:8px}
.panel-title{display:flex;align-items:center;gap:10px}
.panel-header{cursor:grab;user-select:none;touch-action:none}.panel-header.dragging{cursor:grabbing}.panel-actions{cursor:default;touch-action:auto}
.panel-content{padding:0 28px 28px;overflow:auto;overscroll-behavior:contain;min-height:0;flex:0 1 auto}
.panel-content.headerless{padding-top:28px}
.panel-content.with-footer{padding-bottom:12px}
.panel-footer{display:flex;justify-content:flex-end;align-items:center;gap:8px;padding:12px 28px 28px;flex-shrink:0}.panel-footer :slotted(.action-spacer){flex:1}
@media(prefers-reduced-motion:reduce){.elastic-panel{transition:none}}
</style>

// ui/components/ElasticPanel.tsx
import {
  useCallback,
  useEffect,
  useLayoutEffect,
  useRef,
  useState,
  type ReactNode,
  type CSSProperties,
} from "react";
import { Dialog as D } from "radix-ui";
import { X } from "lucide-react";
import { t } from "../i18n";
import {
  panelLayers,
  panelHandoff,
  panelAnchorAt,
  rememberPanel,
} from "../state/panels";
const reduced = () => matchMedia("(prefers-reduced-motion: reduce)").matches;
const easing = "cubic-bezier(.2,.8,.3,1)";
const duration = 480;
const frameAt = (rect: DOMRect, opacity: number, borderRadius: string): Keyframe => ({
  transform: `translate(calc(-50% + ${rect.x + rect.width / 2 - innerWidth / 2}px),calc(-50% + ${rect.y + rect.height / 2 - innerHeight / 2}px))`,
  width: `${rect.width}px`,
  height: `${rect.height}px`,
  opacity,
  borderRadius,
});
export default function ElasticPanel({
  open = true,
  onClose,
  title,
  children,
  footer,
  actions,
  wide = false,
  busy = false,
  unframed = false,
  headerless = false,
  width,
}: {
  open?: boolean;
  onClose: () => void;
  title: ReactNode;
  children: ReactNode;
  footer?: ReactNode;
  actions?: ReactNode;
  wide?: boolean;
  busy?: boolean;
  unframed?: boolean;
  headerless?: boolean;
  width?: number;
}) {
  const [node, setNode] = useState<HTMLDivElement | null>(null),
    [position, setPosition] = useState({ x: 0, y: 0 });
  const panelRef = useRef<HTMLDivElement | null>(null);
  const attach = useCallback((el: HTMLDivElement | null) => {
    panelRef.current = el;
    setNode(el);
  }, []);
  const positionRef = useRef(position);
  positionRef.current = position;
  const trigger = useRef<HTMLElement | null>(
    document.activeElement instanceof HTMLElement
      ? document.activeElement
      : null,
  );
  const origin = useRef<DOMRect | undefined>(
    trigger.current?.getBoundingClientRect(),
  );
  const closing = useRef(false),
    motion = useRef<Animation | null>(null),
    backdropPressed = useRef(false);
  const drag = useRef<
    { id: number; x: number; y: number; left: number; top: number } | undefined
  >(undefined);
  const layers = panelLayers.use(),
    recessed = !!node && layers.includes(node) && layers.at(-1) !== node;
  const latest = useRef({ onClose, busy });
  latest.current = { onClose, busy };
  const moveTo = (x: number, y: number) => {
    if (!node) return;
    const maxX = Math.max(0, (innerWidth - node.offsetWidth) / 2 - 20),
      maxY = Math.max(0, (innerHeight - node.offsetHeight) / 2 - 20);
    setPosition({
      x: Math.max(-maxX, Math.min(maxX, x)),
      y: Math.max(-maxY, Math.min(maxY, y)),
    });
  };
  useLayoutEffect(() => {
    if (!node || !open) return;
    const previous = panelLayers.get().at(-1);
    const handoff =
      (panelHandoff.until ?? 0) > performance.now()
        ? panelHandoff.from
        : undefined;
    const source =
      handoff ?? previous?.getBoundingClientRect() ?? origin.current;
    if (handoff && panelHandoff.trigger) trigger.current = panelHandoff.trigger;
    panelHandoff.from = undefined;
    panelHandoff.trigger = undefined;
    panelLayers.set((old) => [...old, node]);
    const focusFrame = requestAnimationFrame(() =>
      node.focus({ preventScroll: true }),
    );
    const rect = node.getBoundingClientRect();
    if (!reduced() && source && rect.width) {
      motion.current = node.animate(
        [
          frameAt(source, previous || handoff ? 1 : 0, previous || handoff ? "28px" : "50%"),
          frameAt(rect, 1, "28px"),
        ],
        { duration: previous || handoff ? 320 : duration, easing },
      );
      Array.from(node.children).forEach((child) =>
        child.animate([{ opacity: 0 }, { opacity: 1 }], {
          duration: 280,
          delay: 80,
          fill: "backwards",
        }),
      );
    }
    // Keep the natural target height, not the opening animation's trigger height.
    // Otherwise ResizeObserver replays the expansion as soon as opening finishes.
    let height = rect.height,
      resizing: Animation | undefined,
      resizeFrame = 0;
    // Async content can change the natural target while the opening animation
    // still fixes the panel's height. Measure without its effect in the same
    // frame, then retarget it before the browser paints.
    const openingContent = new MutationObserver(() => {
      const animation = motion.current;
      if (closing.current || animation?.playState !== "running") return;
      const effect = animation.effect as KeyframeEffect | null;
      if (!effect) return;
      animation.effect = null;
      const target = node.getBoundingClientRect();
      animation.effect = effect;
      const frames = effect.getKeyframes();
      frames[frames.length - 1].height = `${target.height}px`;
      effect.setKeyframes(frames);
      height = target.height;
    });
    openingContent.observe(node, { childList: true, subtree: true, characterData: true });
    const resize = () => {
      if (
        closing.current ||
        motion.current?.playState === "running" ||
        resizing?.playState === "running"
      )
        return;
      const next = node.offsetHeight;
      if (Math.abs(next - height) > 1 && !reduced()) {
        resizing = node.animate(
          [{ height: `${height}px` }, { height: `${next}px` }],
          { duration: 320, easing },
        );
      }
      height = next;
    };
    const observer = new ResizeObserver(() => {
      cancelAnimationFrame(resizeFrame);
      resizeFrame = requestAnimationFrame(resize);
    });
    observer.observe(node);
    return () => {
      cancelAnimationFrame(focusFrame);
      cancelAnimationFrame(resizeFrame);
      rememberPanel(node, trigger.current ?? undefined);
      panelLayers.set((old) => old.filter((el) => el !== node));
      observer.disconnect();
      openingContent.disconnect();
      resizing?.cancel();
      motion.current?.cancel();
    };
  }, [node, open]);
  useEffect(() => {
    const resize = () => moveTo(positionRef.current.x, positionRef.current.y);
    window.addEventListener("resize", resize);
    return () => window.removeEventListener("resize", resize);
  }, [node]);
  async function close(replacement?: HTMLElement) {
    if (latest.current.busy || closing.current || !node) return;
    closing.current = true;
    const previous = panelLayers.get().at(-2),
      from = node.getBoundingClientRect(),
      to =
        previous?.getBoundingClientRect() ??
        (trigger.current?.isConnected
          ? trigger.current.getBoundingClientRect()
          : origin.current);
    if (replacement) {
      rememberPanel(node, replacement);
    } else if (to && !reduced()) {
      const style = getComputedStyle(node);
      const current = frameAt(from, Number(style.opacity), style.borderRadius);
      const closeDuration = previous ? 320 : duration;
      motion.current?.cancel();
      motion.current = node.animate(
        [
          current,
          frameAt(to, previous ? 1 : 0, previous ? "28px" : "50%"),
        ],
        { duration: closeDuration, easing, fill: "forwards" },
      );
      Array.from(node.children).forEach((child) => {
        const opacity = getComputedStyle(child).opacity;
        child.getAnimations().forEach((animation) => animation.cancel());
        child.animate([{ opacity: 0 }, { opacity }], {
          duration: 280,
          delay: Math.max(0, closeDuration - 360),
          direction: "reverse",
          fill: "both",
        });
      });
      await motion.current.finished.catch(() => {});
    }
    latest.current.onClose();
    if (replacement)
      requestAnimationFrame(() => {
        panelHandoff.trigger = replacement;
        panelHandoff.from = from;
        panelHandoff.until = performance.now() + 100;
        replacement.focus({ preventScroll: true });
        replacement.click();
      });
  }
  return (
    <D.Root
      open={open}
      onOpenChange={(next) => {
        if (!next) void close();
      }}
    >
      <D.Portal>
        <D.Overlay
          className="elastic-backdrop"
          style={{ zIndex: 100 + Math.max(0, layers.indexOf(node!)) * 2 }}
          onPointerDown={(e) => {
            backdropPressed.current =
              e.button === 0 && e.target === e.currentTarget;
          }}
          onPointerCancel={() => (backdropPressed.current = false)}
          onClick={(e) => {
            if (backdropPressed.current && e.target === e.currentTarget) {
              backdropPressed.current = false;
              void close(
                panelAnchorAt(
                  e.clientX,
                  e.clientY,
                  trigger.current ?? undefined,
                ),
              );
            }
          }}
        />
        <D.Content
          ref={attach}
          className={`dialog elastic-panel ${wide ? "dialog-wide" : ""} ${unframed ? "unframed" : ""} ${headerless ? "headerless" : ""}`}
          data-recessed={recessed || undefined}
          aria-describedby={undefined}
          style={
            {
              "--preferred-width": `${width ?? (wide ? 880 : 800)}px`,
              transform: `translate(calc(-50% + ${position.x}px),calc(-50% + ${position.y}px))`,
              zIndex: 101 + Math.max(0, layers.indexOf(node!)) * 2,
            } as CSSProperties
          }
          onOpenAutoFocus={(e) => {
            e.preventDefault();
            panelRef.current?.focus({ preventScroll: true });
          }}
          onCloseAutoFocus={(e) => {
            e.preventDefault();
            if (trigger.current?.isConnected)
              trigger.current.focus({ preventScroll: true });
          }}
          onEscapeKeyDown={(e) => {
            e.preventDefault();
            void close();
          }}
          onPointerDownOutside={(e) => e.preventDefault()}
        >
          {unframed || headerless ? (
            <D.Title className="sr-only">{title}</D.Title>
          ) : (
            <header
              className="dialog-header"
              onPointerDown={(e) => {
                if (
                  e.button !== 0 ||
                  !e.isPrimary ||
                  (e.target as Element).closest("button") ||
                  motion.current?.playState === "running"
                )
                  return;
                drag.current = {
                  id: e.pointerId,
                  x: e.clientX,
                  y: e.clientY,
                  left: position.x,
                  top: position.y,
                };
                e.currentTarget.setPointerCapture(e.pointerId);
                e.preventDefault();
              }}
              onPointerMove={(e) => {
                const d = drag.current;
                if (d && d.id === e.pointerId)
                  moveTo(d.left + e.clientX - d.x, d.top + e.clientY - d.y);
              }}
              onPointerUp={(e) => {
                drag.current = undefined;
                if (e.currentTarget.hasPointerCapture(e.pointerId))
                  e.currentTarget.releasePointerCapture(e.pointerId);
              }}
              onPointerCancel={() => (drag.current = undefined)}
            >
              <D.Title>{title}</D.Title>
              <div className="actions">
                {actions}
                <button
                  type="button"
                  className="button ghost icon-button"
                  aria-label={t("close")}
                  disabled={busy}
                  onClick={() => void close()}
                >
                  <X size={20} strokeWidth={1.75} />
                </button>
              </div>
            </header>
          )}
          <div className="dialog-body">{children}</div>
          {footer && <footer className="dialog-footer">{footer}</footer>}
        </D.Content>
      </D.Portal>
    </D.Root>
  );
}
