// ui/components/IngressDetailsDialog.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue';
import { NAlert, NButton, NForm, NFormItem } from 'naive-ui';
import { api, useConnector, type Ingress } from '../composables/useConnector';
import { t } from '../i18n';
import { displayMessage } from '../messages';
import ElasticPanel from './ElasticPanel.vue';
import CopyField from './CopyField.vue';
import OAuthGrants from './OAuthGrants.vue';

const props = defineProps<{ ingress: Ingress; autoConnect?: boolean }>();
const open = ref(true);
const editing = ref(false);
const emit = defineEmits<{ close: []; edit: [ingress: Ingress] }>();
const { status, refresh } = useConnector();
const entry = computed(() => status.value?.ingresses.find(i => i.id === props.ingress.id) || props.ingress);
const https = computed(() => entry.value.transport === 'https');
const endpoint = computed(() => {
  if (!https.value) return entry.value.config.tunnelId;
  if (entry.value.url) return entry.value.url;
  const config = entry.value.config;
  if (config.httpsProvider === 'pinggy' && config.pinggyMode === 'named' || config.httpsProvider === 'localxpose' && config.localxposeMode === 'named') return config.httpsUrl;
  if (config.httpsProvider === 'custom' || config.httpsProvider === 'cloudflare' && config.cloudflareMode === 'named') return config.httpsUrl;
  if (config.httpsProvider === 'ngrok' && config.ngrokMode === 'named' && config.ngrokEndpoint) {
    const domain = config.ngrokEndpoint;
    return new URL(domain.includes('://') ? domain : `https://${domain}`).origin + '/mcp';
  }
  return '';
});
const reverseProxy = computed(() => {
  const config = entry.value.config;
  return `http://${config.httpsHost.includes(':') ? `[${config.httpsHost}]` : config.httpsHost}:${config.httpsPort}/mcp`;
});
const working = ref(false), reading = ref(false), error = ref(''), credentialError = ref(''), bearerToken = ref(''), apiKey = ref('');
const refreshingUrl = ref(false), oauthBusy = ref(false);
const connecting = computed(() => working.value || oauthBusy.value || entry.value.state === 'starting');
let disposed = false;
async function readCredentials() {
  if (!['bearer', 'openai'].includes(entry.value.auth)) return;
  reading.value = true;
  credentialError.value = '';
  try {
    const credentials = await api<{ bearerToken?: string; apiKey?: string }>(`ingress/${entry.value.id}/credentials`, 'POST');
    if (!disposed) { bearerToken.value = credentials.bearerToken || ''; apiKey.value = credentials.apiKey || ''; }
  } catch { if (!disposed) credentialError.value = t('credentialReadFailed'); }
  finally { if (!disposed) reading.value = false; }
}
async function connect() {
  if (connecting.value) return;
  working.value = true;
  error.value = '';
  try { await api(`ingress/${entry.value.id}/start`, 'POST'); }
  catch (e) { if (!disposed) error.value = e instanceof Error ? e.message : String(e); }
  finally { await refresh().catch(() => {}); if (!disposed) working.value = false; }
}
async function updateConnection(kind: 'url' | 'token') {
  if (connecting.value || reading.value) return;
  const id = entry.value.id;
  const restart = kind === 'url' ? entry.value.config.httpsProvider !== 'custom' : entry.value.running;
  working.value = true;
  refreshingUrl.value = restart;
  error.value = '';
  let stopped = false;
  try {
    if (restart) { await api(`ingress/${id}/stop`, 'POST'); stopped = true; }
    if (kind === 'token') {
      const result = await api<{ token: string }>(`ingress/${id}/token`, 'POST');
      if (!disposed) { bearerToken.value = result.token; credentialError.value = ''; }
    }
  } catch (e) { if (!disposed) error.value = e instanceof Error ? e.message : String(e); }
  finally {
    if (stopped) {
      try { await api(`ingress/${id}/start`, 'POST'); }
      catch (e) { if (!disposed) error.value = [error.value, e instanceof Error ? e.message : String(e)].filter(Boolean).join('\n'); }
    }
    await refresh().catch(e => { if (!disposed) error.value = String(e); });
    if (!disposed) { working.value = false; refreshingUrl.value = false; }
  }
}
onMounted(() => {
  void readCredentials();
  if (props.autoConnect) void connect();
});
onUnmounted(() => { disposed = true; bearerToken.value = ''; apiKey.value = ''; });
</script>

<template>
  <ElasticPanel :show="open" :width="600" :title="t('connectionDetails') + ' · ' + entry.name" :busy="working || oauthBusy" @close="open=false" @closed="editing ? emit('edit',entry) : emit('close')">
    <NForm label-placement="top">
      <NFormItem :label="https ? 'MCP URL' : 'Tunnel ID'" :label-style="{width:'100%',display:'grid',gridTemplateColumns:'minmax(0,1fr)'}">
        <template #label><span class="detail-heading"><span>{{https ? 'MCP URL' : 'Tunnel ID'}}</span><NButton v-if="https" :aria-label="t('reobtainMcpUrl')" text type="primary" size="tiny" :disabled="connecting || reading || !entry.enabled" @click="updateConnection('url')">{{t('reobtainMcpUrl')}}</NButton></span></template>
        <CopyField :value="refreshingUrl ? '' : endpoint" :label="https ? 'MCP URL' : 'Tunnel ID'" :loading="https && (refreshingUrl || !endpoint && connecting)" :placeholder="connecting ? t('fetchingMcpUrl') : t('generatedWhenConnected')"/>
      </NFormItem>
      <NFormItem v-if="entry.auth === 'bearer'" label="Bearer token" :label-style="{width:'100%',display:'grid',gridTemplateColumns:'minmax(0,1fr)'}">
        <template #label><span class="detail-heading"><span>Bearer token</span><NButton :aria-label="t('generateNewToken')" text type="primary" size="tiny" :disabled="connecting || reading" @click="updateConnection('token')">{{t('generateNewToken')}}</NButton></span></template>
        <CopyField :value="bearerToken" label="Bearer token" password :placeholder="credentialError || ''"/>
      </NFormItem>
      <NFormItem v-if="entry.auth === 'openai'" label="Runtime API Key">
        <CopyField :value="apiKey" label="Runtime API Key" password :placeholder="credentialError || ''"/>
      </NFormItem>
      <OAuthGrants v-if="entry.auth === 'oauth'" :key="entry.id" :ingress-id="entry.id" :running="entry.running" :disabled="working" @busy="oauthBusy=$event"/>
      <NAlert v-if="credentialError" :show-icon="false" type="error">{{credentialError}} <NButton text :disabled="reading" @click="readCredentials">{{t('retry')}}</NButton></NAlert>
      <NFormItem v-if="https && (entry.config.httpsProvider === 'custom' || entry.config.httpsProvider === 'cloudflare' && entry.config.cloudflareMode === 'named')" :label="t('httpReverseProxyTarget')">
        <CopyField :value="reverseProxy" :label="t('httpReverseProxyTarget')"/>
      </NFormItem>
      <NAlert v-if="error || entry.error" :show-icon="false" type="error">{{displayMessage(error || entry.error)}}</NAlert>
    </NForm>
    <template #footer>
      <NButton :disabled="connecting" @click="editing=true; open=false">{{t('edit')}}</NButton>
      <span class="action-spacer"/>
      <NButton v-if="!entry.running && !connecting" :disabled="!entry.enabled" @click="connect">{{t('connect')}}</NButton>
      <NButton type="primary" :disabled="working || oauthBusy" @click="open=false">{{t('done')}}</NButton>
    </template>
  </ElasticPanel>
</template>

<style scoped>.detail-heading{display:flex;align-items:center;justify-content:space-between;gap:16px;width:100%}</style>

// ui/components/IngressDetailsDialog.tsx
import { useEffect, useRef, useState } from "react";
import { api } from "../api";
import { t } from "../i18n";
import { displayMessage } from "../messages";
import { connector, refreshConnector } from "../state/connector";
import type { Ingress } from "../state/types";
import {
  Button,
  CopyField,
  Dialog,
  DialogClose,
  Field,
  Notice,
  Status,
} from "./ui";
import OAuthGrants from "./OAuthGrants";
export default function IngressDetailsDialog({
  ingress,
  autoConnect = false,
  onClose,
  onEdit,
}: {
  ingress: Ingress;
  autoConnect?: boolean;
  onClose: () => void;
  onEdit: (ingress: Ingress) => void;
}) {
  const { status } = connector.use();
  const entry = status?.ingresses.find((i) => i.id === ingress.id) || ingress;
  const [working, setWorking] = useState(false),
    [oauthBusy, setOauthBusy] = useState(false),
    [reading, setReading] = useState(false),
    [error, setError] = useState(""),
    [credentialError, setCredentialError] = useState(""),
    [credentials, setCredentials] = useState<{
      bearerToken?: string;
      apiKey?: string;
    }>({}),
    [refreshingUrl, setRefreshingUrl] = useState(false);
  const alive = useRef(true);
  const https = entry.transport === "https",
    connecting = working || oauthBusy || entry.state === "starting";
  let endpoint = https ? entry.url : entry.config.tunnelId;
  const c = entry.config;
  if (https && !endpoint) {
    if (
      c.httpsProvider === "custom" ||
      (c.httpsProvider === "cloudflare" && c.cloudflareMode === "named") ||
      (c.httpsProvider === "pinggy" && c.pinggyMode === "named") ||
      c.httpsProvider === "localxpose"
    )
      endpoint = c.httpsUrl;
    else if (
      c.httpsProvider === "ngrok" &&
      c.ngrokMode === "named" &&
      c.ngrokEndpoint
    ) {
      try {
        endpoint =
          new URL(
            c.ngrokEndpoint.includes("://")
              ? c.ngrokEndpoint
              : `https://${c.ngrokEndpoint}`,
          ).origin + "/mcp";
      } catch {
        endpoint = "";
      }
    }
  }
  async function readCredentials() {
    if (!["bearer", "openai"].includes(entry.auth)) return;
    setReading(true);
    setCredentialError("");
    try {
      const value = await api<typeof credentials>(
        `ingress/${entry.id}/credentials`,
        "POST",
      );
      if (alive.current) setCredentials(value);
    } catch {
      if (alive.current) setCredentialError(t("credentialReadFailed"));
    } finally {
      if (alive.current) setReading(false);
    }
  }
  async function connect() {
    if (connecting) return;
    setWorking(true);
    setError("");
    try {
      await api(`ingress/${entry.id}/start`, "POST");
    } catch (e) {
      if (alive.current) setError(String(e));
    } finally {
      await refreshConnector().catch(() => {});
      if (alive.current) setWorking(false);
    }
  }
  async function updateConnection(kind: "url" | "token") {
    if (connecting || reading) return;
    const restart =
      kind === "url" ? c.httpsProvider !== "custom" : entry.running;
    setWorking(true);
    setRefreshingUrl(restart);
    setError("");
    let stopped = false;
    try {
      if (restart) {
        await api(`ingress/${entry.id}/stop`, "POST");
        stopped = true;
      }
      if (kind === "token") {
        const result = await api<{ token: string }>(
          `ingress/${entry.id}/token`,
          "POST",
        );
        setCredentials((old) => ({ ...old, bearerToken: result.token }));
        setCredentialError("");
      }
    } catch (e) {
      setError(String(e));
    } finally {
      if (stopped)
        try {
          await api(`ingress/${entry.id}/start`, "POST");
        } catch (e) {
          setError((old) => [old, String(e)].filter(Boolean).join("\n"));
        }
      await refreshConnector().catch((e) => setError(String(e)));
      setWorking(false);
      setRefreshingUrl(false);
    }
  }
  useEffect(() => {
    alive.current = true;
    void readCredentials();
    if (autoConnect) void connect();
    return () => {
      alive.current = false;
    };
  }, []);
  return (
    <Dialog
      title={
        <span className="ingress-dialog-title">
          {entry.name}
          <Status
            tone={entry.error ? "danger" : entry.running ? "success" : "neutral"}
          >
            {t(
              entry.error
                ? "connectionError"
                : entry.running
                  ? "connected"
                  : entry.state === "starting"
                    ? "connectingLabel"
                    : "disconnected",
            )}
          </Status>
        </span>
      }
      onClose={onClose}
      busy={working || oauthBusy}
      footer={
        <>
          <Button disabled={connecting} onClick={() => onEdit(entry)}>
            {t("edit")}
          </Button>
          <span className="spacer" />
          {!entry.running && !connecting && (
            <Button disabled={!entry.enabled} onClick={() => void connect()}>
              {t("connect")}
            </Button>
          )}
          <DialogClose asChild>
            <Button variant="primary" disabled={working || oauthBusy}>
              {t("done")}
            </Button>
          </DialogClose>
        </>
      }
    >
      <div className="form">

        <Field
          label={https ? "MCP URL" : "Tunnel ID"}
          help={
            https && (
              <Button
                variant="ghost"
                disabled={connecting || reading || !entry.enabled}
                onClick={() => void updateConnection("url")}
              >
                {t("reobtainMcpUrl")}
              </Button>
            )
          }
        >
          <CopyField
            value={refreshingUrl ? "" : endpoint || ""}
            label={https ? "MCP URL" : "Tunnel ID"}
            loading={https && (refreshingUrl || (!endpoint && connecting))}
            placeholder={t(
              connecting ? "fetchingMcpUrl" : "generatedWhenConnected",
            )}
          />
        </Field>
        {entry.auth === "bearer" && (
          <Field
            label="Bearer token"
            help={
              <Button
                variant="ghost"
                disabled={connecting || reading}
                onClick={() => void updateConnection("token")}
              >
                {t("generateNewToken")}
              </Button>
            }
          >
            <CopyField
              value={credentials.bearerToken || ""}
              label="Bearer token"
              password
              loading={reading}
            />
          </Field>
        )}
        {entry.auth === "openai" && (
          <Field label="Runtime API Key">
            <CopyField
              value={credentials.apiKey || ""}
              label="Runtime API Key"
              password
              loading={reading}
            />
          </Field>
        )}
        {entry.auth === "oauth" && (
          <OAuthGrants
            ingressId={entry.id}
            running={entry.running}
            disabled={working}
            onBusy={setOauthBusy}
          />
        )}
        {credentialError && (
          <Notice
            action={
              <Button disabled={reading} onClick={() => void readCredentials()}>
                {t("retry")}
              </Button>
            }
          >
            {credentialError}
          </Notice>
        )}
        {https &&
          (c.httpsProvider === "custom" ||
            (c.httpsProvider === "cloudflare" &&
              c.cloudflareMode === "named")) && (
            <Field label={t("httpReverseProxyTarget")}>
              <CopyField
                value={`http://${c.httpsHost.includes(":") ? `[${c.httpsHost}]` : c.httpsHost}:${c.httpsPort}/mcp`}
                label={t("httpReverseProxyTarget")}
              />
            </Field>
          )}
        {(error || entry.error) && (
          <Notice>{displayMessage(error || entry.error)}</Notice>
        )}
      </div>
    </Dialog>
  );
}
