// ui/components/IngressDialog.vue
<script setup lang="ts">
import { ref, reactive, computed, onUnmounted, watch } from 'vue';
import { NForm, NFormItem, NInput, NButton, NAlert, NText, type FormInst } from 'naive-ui';
import ElasticPanel from './ElasticPanel.vue';
import ToolPolicyField from './ToolPolicyField.vue';
import type { ToolPolicy } from '../toolPolicy';
import SourceIcon from './SourceIcon.vue';
import { required, domainRule, validDomain } from '../formRules';
import { t } from '../i18n';
import { controlSource, curatedSources, nextSourceName } from '../controlSources';
import { openUrl } from '../platform';
import SingleChoice from './SingleChoice.vue';
import { displayMessage } from '../messages';
import { api, useConnector, type Ingress } from '../composables/useConnector';
import { connectionForm } from '../composables/connectionForm';
import ConnectionFields from './ConnectionFields.vue';
import { providers, needsCredential, credentialSaved, clearCredentials, secretFields, fixedDomain } from '../ingressConfig';

const props = defineProps<{ origin: { x: number; y: number; size: number }; ingress?: Ingress; defaultChatGPT?: boolean }>();
const emit = defineEmits<{ close: []; saved: [ingress: Ingress] }>();
const panelOpen = ref(true);
const hasPicker = !props.ingress && !props.defaultChatGPT;
const formOpen = ref(!hasPicker);
const formOrigin = ref(props.origin);
function formClosed() {
  if (!hasPicker) { panelClosed(); return; }
  if (savedIngress) panelOpen.value = false;
  else selected.value = '';
}
let savedIngress: Ingress | undefined;
function panelClosed() { savedIngress ? emit('saved', savedIngress) : emit('close'); }
const { refresh, status } = useConnector();
const formRef = ref<FormInst>();
const presetNames = Object.fromEntries(curatedSources.map(p => [p.id, p.displayName]));
const entry = ref(props.ingress);
const toolPolicy = ref<ToolPolicy>(props.ingress?.toolPolicy ?? 'all');
const providerReady = computed(() => {
  const key = providers[form.httpsProvider].credential;
  return !needsCredential(form) || !!key && !!(form[key].trim() || credentialSaved(entry.value?.config, key));
});
const canSave = computed(() => !!name.value.trim() && new TextEncoder().encode(name.value).length<=120
  && (selected.value!=='custom' || /^[a-zA-Z0-9_-]+$/.test(source.value))
  && (form.connectionMode==='tunnel'
    ? /^tunnel_[a-zA-Z0-9_-]+$/.test(form.tunnelId) && !!(form.apiKey.trim() || entry.value?.config.hasApiKey)
    : providerReady.value
      && (!fixedDomain(form) || validDomain(form.domain))));
function configPayload() {
  const config:Record<string,unknown>={...form};
  delete config.connectionMode;
  delete config.domain;
  const fixed = fixedDomain(form);
  const origin = fixed && form.domain.trim() ? `https://${form.domain.trim()}` : '';
  config.httpsUrl = origin ? `${origin}/mcp` : '';
  config.ngrokEndpoint = form.httpsProvider==='ngrok' ? origin : '';
  if(!entry.value) { delete config.httpsPort; delete config.httpsHost; }
  for(const { key } of secretFields) if(!config[key]) delete config[key];
  return config;
}
const selected = ref(props.ingress ? (controlSource(props.ingress.controlSource)?.curated ? props.ingress.controlSource : 'custom') : props.defaultChatGPT ? 'chatgpt' : '');
const source = ref(props.ingress?.controlSource || '');
const name = ref(props.ingress?.name || nextSourceName(selected.value || 'chatgpt', status.value?.ingresses.map(i=>i.name) || []));
const preset = computed(() => controlSource(selected.value));
const form = reactive(connectionForm(props.ingress?.config));
if(!form.domain && props.ingress?.url && (form.httpsProvider==='custom' || form.httpsProvider==='cloudflare' && form.cloudflareMode==='named')) form.domain=new URL(props.ingress.url).hostname;
if (props.ingress) form.connectionMode=props.ingress.transport==='openai-tunnel' ? 'tunnel' : 'https';
else if (preset.value) form.connectionMode=preset.value.recommendedTransport==='openai-tunnel' ? 'tunnel' : 'https';
const auth = ref(props.ingress?.auth === 'oauth' ? 'oauth' : props.ingress?.auth === 'bearer' ? 'bearer' : 'none');
const working = ref(false), error = ref('');
function generateToken() {
  const bytes = crypto.getRandomValues(new Uint8Array(32));
  return Array.from(bytes, byte => byte.toString(16).padStart(2,'0')).join('');
}
watch([()=>form.connectionMode,()=>form.httpsProvider,()=>form.cloudflareMode,()=>form.ngrokMode,()=>form.pinggyMode,()=>form.localxposeMode],()=>{
  form.domain='';
});
onUnmounted(() => { clearCredentials(form); });
const model = computed(() => ({...form, name:name.value, source:source.value}));
function choose(value: string, event: MouseEvent) {
  const button = event.currentTarget as HTMLElement;
  const rect = (button.querySelector('.platform-icon') || button).getBoundingClientRect();
  formOrigin.value = { x: rect.x, y: rect.y, size: rect.width };
  Object.assign(form, connectionForm());
  toolPolicy.value = 'all'; error.value = '';
  selected.value = value; source.value = value === 'custom' ? '' : value;
  name.value = value==='custom' ? '' : nextSourceName(value, status.value?.ingresses.map(i=>i.name) || []);
  form.connectionMode = preset.value?.recommendedTransport==='openai-tunnel' ? 'tunnel' : 'https';
  form.cloudflareMode = form.connectionMode==='tunnel' ? 'quick' : 'named';
  auth.value = preset.value?.httpsAuth ?? 'bearer';
  formOpen.value = true;
}
async function action(fn: () => Promise<void>) {
  working.value = true; error.value = '';
  try { await fn(); } catch(e) { error.value = e instanceof Error ? e.message : String(e); }
  finally { await refresh().catch(() => {}); working.value = false; }
}
async function save() {
  if (working.value || !canSave.value) return;
  try { await formRef.value?.validate(); } catch { return; }
  await action(async () => {
    const bearer=form.connectionMode==='https' && auth.value==='bearer';
    const metadata={toolPolicy:toolPolicy.value,name:name.value.trim(),controlSource:selected.value==='custom' ? source.value : selected.value,auth:form.connectionMode==='tunnel' ? 'openai' : auth.value,
      ...(bearer && entry.value?.auth!=='bearer' ? {bearerToken:generateToken()} : {})};
    if(entry.value) await api(`ingress/${entry.value.id}/stop`,'POST');
    const saved=await api<Ingress>(entry.value ? `ingress/${entry.value.id}` : 'ingress',entry.value ? 'PUT':'POST',{...metadata,transport:form.connectionMode==='tunnel' ? 'openai-tunnel':'https',config:configPayload()});
    entry.value=saved;
    clearCredentials(form);
    await refresh().catch(() => {});
    savedIngress=saved; formOpen.value=false;
  });
}
async function remove() { await action(async () => { await api(`ingress/${entry.value!.id}`, 'DELETE'); formOpen.value=false; }); }
</script>
<template>
  <ElasticPanel :continuation="!!savedIngress" v-if="hasPicker" :show="panelOpen" :origin="origin" :width="600" :title="t('addControlSource')" @close="panelOpen=false" @closed="panelClosed">
    <div class="source-choices"><NButton v-for="option in [...curatedSources.map(p=>p.id),'custom']" :key="option" text :aria-label="presetNames[option] || t('customControlSource')" :title="presetNames[option] || t('customControlSource')" @click="choose(option,$event)"><span class="source-choice"><SourceIcon :platform="option" :add="option==='custom'"/><span>{{presetNames[option] || t('customControlSource')}}</span></span></NButton></div>
  </ElasticPanel>
  <ElasticPanel :continuation="!!savedIngress" :show="formOpen" :origin="formOrigin" :width="600" :title="(entry ? t('editControlSource') : t('addControlSource')) + (selected ? ' · ' + (presetNames[selected] || t('customControlSource')) : '')" :busy="working" @close="formOpen=false" @closed="formClosed">

    <NForm v-if="selected" ref="formRef" :model="model" :disabled="working" label-placement="top" @submit.prevent="save()">
      <NAlert :show-icon="false" v-if="form.connectionMode==='https' && auth==='bearer' && preset && !preset.supportedAuth.includes('bearer')" type="warning">{{t('presetAuthMismatch')}}</NAlert>
      <NFormItem :label="t('sourceName')" path="name" :rule="required()" :show-require-mark="false" :label-props="{for:''}" :label-style="{width:'100%',display:'grid',gridTemplateColumns:'minmax(0,1fr)'}"><template #label><span class="token-heading"><span>{{t('sourceName')}} <NText type="error">*</NText></span><NButton v-if="preset?.docs[0]" text type="primary" size="tiny" @click="openUrl(preset.docs[0])">{{t('officialSetup')}}</NButton></span></template><NInput v-model:value="name" :input-props="{'aria-label':t('sourceName')}"/></NFormItem>
      <NFormItem v-if="selected==='custom'" :label="t('controlSourceId')" path="source" :rule="[{...required()}, {pattern:/^[a-zA-Z0-9_-]+$/,message:t('validClientId'),trigger:'input'}]"><NInput :input-props="{'aria-label':t('controlSourceId')}" v-model:value="source" placeholder="my-client"/></NFormItem>
      <ConnectionFields :recommend-tunnel="selected==='chatgpt'" :form="form" :config="entry?.config" :disabled="working" :allow-tunnel="preset?.recommendedTransport==='openai-tunnel' || selected==='custom'">
        <template #domain>
          <NFormItem v-if="form.httpsProvider==='custom' || form.httpsProvider==='cloudflare' && form.cloudflareMode==='named'" :label="t('domain')" path="domain" :rule="domainRule()" :show-require-mark="false" :label-props="{for:''}" :label-style="{width:'100%',display:'grid',gridTemplateColumns:'minmax(0,1fr)'}">
            <template #label><span class="token-heading"><span>{{t('domain')}} <NText type="error">*</NText></span><NButton v-if="form.httpsProvider==='cloudflare'" text type="primary" :aria-label="t('getDomain')" size="tiny" @click="openUrl('https://dash.cloudflare.com/?to=/:account/tunnels')">{{t('getDomain')}}</NButton></span></template>
            <div class="url-field">
              <NInput v-model:value="form.domain" :input-props="{'aria-label':t('domain')}" placeholder="mcp.example.com"/>
            </div>
          </NFormItem>
        </template>
      </ConnectionFields>
      <template v-if="form.connectionMode==='https'">
        <NFormItem :label="t('authentication')" path="auth"><SingleChoice v-model:value="auth" :label="t('authentication')" :disabled="working" :options="[{label:t('authNone'),value:'none'},{label:'Bearer',value:'bearer'},{label:'OAuth',value:'oauth'}]"/></NFormItem>

      </template>

      <ToolPolicyField v-model:value="toolPolicy" :disabled="working"/>
      <NAlert :show-icon="false" v-if="error" type="error" role="alert">{{displayMessage(error)}}</NAlert>
    </NForm>
    <template v-if="selected" #footer>
      <NButton v-if="entry" type="error" secondary :disabled="working" @click="remove">{{t('remove')}}</NButton>
      <span class="action-spacer"/>
      <NButton :disabled="working" @click="formOpen=false">{{t('cancel')}}</NButton>
      <NButton type="primary" :disabled="working || !canSave" :loading="working" @click="save()">{{t('save')}}</NButton>
    </template>
  </ElasticPanel>
</template>
<style scoped>.url-field{width:100%;display:grid;gap:10px}.token-heading{display:flex;align-items:center;justify-content:space-between;gap:16px;width:100%}.source-choices{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;padding:12px 0}.source-choices .n-button{height:116px;white-space:normal}.source-choice{display:flex;flex-direction:column;align-items:center;gap:8px;font-size:13px}</style>

// ui/components/IngressDialog.tsx
import { useState, useRef } from "react";
import { api } from "../api";
import { t } from "../i18n";
import { displayMessage } from "../messages";
import { openUrl } from "../platform";
import {
  controlSource,
  curatedSources,
  nextSourceName,
} from "../controlSources";
import {
  providers,
  fixedDomain,
  needsCredential,
  credentialSaved,
  secretFields,
} from "../ingressConfig";
import { validDomain } from "../formRules";
import { connectionForm, type ConnectionForm } from "../state/connectionForm";
import { connector, refreshConnector } from "../state/connector";
import type { Ingress } from "../state/types";
import type { ToolPolicy } from "../toolPolicy";
import {
  Button,
  Dialog,
  DialogClose,
  Field,
  Input,
  Notice,
  SingleChoice,
} from "./ui";
import SourceIcon from "./SourceIcon";
import ToolPolicyField from "./ToolPolicyField";
export default function IngressDialog({
  ingress,
  onClose,
  onSaved,
}: {
  ingress?: Ingress;
  onClose: () => void;
  onSaved: (ingress: Ingress) => void;
}) {
  const { status } = connector.use();
  const [selected, setSelected] = useState(
    ingress
      ? controlSource(ingress.controlSource)?.curated
        ? ingress.controlSource
        : "custom"
      : "",
  );
  const [source, setSource] = useState(ingress?.controlSource || ""),
    [name, setName] = useState(ingress?.name || ""),
    [form, setForm] = useState(() => {
      const f = connectionForm(ingress?.config);
      if (ingress)
        f.connectionMode =
          ingress.transport === "openai-tunnel" ? "tunnel" : "https";
      return f;
    });
  const [auth, setAuth] = useState(
      ingress?.auth === "oauth"
        ? "oauth"
        : ingress?.auth === "bearer"
          ? "bearer"
          : "none",
    ),
    [toolPolicy, setToolPolicy] = useState<ToolPolicy>(
      ingress?.toolPolicy ?? "all",
    );
  const [working, setWorking] = useState(false),
    [error, setError] = useState(""),
    [errors, setErrors] = useState<Record<string, string>>({});
  const formRef = useRef<HTMLFormElement>(null);
  const preset = controlSource(selected),
    provider = providers[form.httpsProvider],
    https = form.connectionMode === "https",
    allowTunnel =
      preset?.recommendedTransport === "openai-tunnel" || selected === "custom";
  function change<K extends keyof ConnectionForm>(
    key: K,
    value: ConnectionForm[K],
  ) {
    setForm((old) => ({
      ...old,
      [key]: value,
      ...([
        "connectionMode",
        "httpsProvider",
        "cloudflareMode",
        "ngrokMode",
        "pinggyMode",
        "localxposeMode",
      ].includes(key)
        ? { domain: "" }
        : {}),
    }));
    setErrors((old) => ({ ...old, [key]: "" }));
  }
  function choose(value: string) {
    const preset = controlSource(value),
      f = connectionForm();
    f.connectionMode =
      preset?.recommendedTransport === "openai-tunnel" ? "tunnel" : "https";
    f.cloudflareMode = f.connectionMode === "tunnel" ? "quick" : "named";
    setSelected(value);
    setSource(value === "custom" ? "" : value);
    setName(
      value === "custom"
        ? ""
        : nextSourceName(value, status?.ingresses.map((i) => i.name) || []),
    );
    setForm(f);
    setAuth(preset?.httpsAuth ?? "bearer");
    setErrors({});
  }
  function validate() {
    const next: Record<string, string> = {};
    if (!name.trim()) next.name = t("fieldRequired");
    else if (new TextEncoder().encode(name).length > 120)
      next.name = t("sourceNameTooLong");
    if (selected === "custom" && !/^[a-zA-Z0-9_-]+$/.test(source))
      next.source = t("validClientId");
    if (!https) {
      if (!/^tunnel_[a-zA-Z0-9_-]+$/.test(form.tunnelId))
        next.tunnelId = t("validTunnelId");
      if (!form.apiKey.trim() && !ingress?.config.hasApiKey)
        next.apiKey = t("fieldRequired");
    } else {
      if (fixedDomain(form) && !validDomain(form.domain))
        next.domain = t("validDomain");
      const key = provider.credential;
      if (
        needsCredential(form) &&
        key &&
        !form[key].trim() &&
        !credentialSaved(ingress?.config, key)
      )
        next[key] = t("fieldRequired");
    }
    setErrors(next);
    if (Object.keys(next).length) {
      requestAnimationFrame(() =>
        formRef.current
          ?.querySelector<HTMLElement>("[aria-invalid=true]")
          ?.focus(),
      );
      return false;
    }
    return true;
  }
  async function save() {
    if (working || !validate()) return;
    setWorking(true);
    setError("");
    try {
      const config: Record<string, unknown> = { ...form };
      delete config.connectionMode;
      delete config.domain;
      const origin = fixedDomain(form) ? `https://${form.domain.trim()}` : "";
      config.httpsUrl = origin ? `${origin}/mcp` : "";
      config.ngrokEndpoint = form.httpsProvider === "ngrok" ? origin : "";
      if (!ingress) {
        delete config.httpsPort;
        delete config.httpsHost;
      }
      for (const { key } of secretFields) if (!config[key]) delete config[key];
      const bearer = https && auth === "bearer";
      const metadata = {
        toolPolicy,
        name: name.trim(),
        controlSource: selected === "custom" ? source : selected,
        auth: https ? auth : "openai",
        ...(bearer && ingress?.auth !== "bearer"
          ? {
              bearerToken: Array.from(
                crypto.getRandomValues(new Uint8Array(32)),
                (byte) => byte.toString(16).padStart(2, "0"),
              ).join(""),
            }
          : {}),
      };
      if (ingress) await api(`ingress/${ingress.id}/stop`, "POST");
      const saved = await api<Ingress>(
        ingress ? `ingress/${ingress.id}` : "ingress",
        ingress ? "PUT" : "POST",
        { ...metadata, transport: https ? "https" : "openai-tunnel", config },
      );
      await refreshConnector().catch(() => {});
      onSaved(saved);
    } catch (e) {
      setError(String(e));
    } finally {
      setWorking(false);
    }
  }
  async function remove() {
    if (!ingress || working) return;
    setWorking(true);
    setError("");
    try {
      await api(`ingress/${ingress.id}`, "DELETE");
      await refreshConnector();
      onClose();
    } catch (e) {
      setError(String(e));
    } finally {
      setWorking(false);
    }
  }
  const textField = (
    key: keyof ConnectionForm,
    label: string,
    password = false,
    placeholder = "",
    help?: string,
  ) => (
    <Field
      id={`ingress-${key}`}
      label={label}
      error={errors[key]}
      help={
        help && (
          <Button
            variant="ghost"
            onClick={() => void openUrl(help).catch((e) => setError(String(e)))}
          >
            {t("getCredentials")}
          </Button>
        )
      }
    >
      <Input
        id={`ingress-${key}`}
        aria-invalid={!!errors[key]}
        aria-describedby={errors[key] ? `ingress-${key}-error` : undefined}
        type={password ? "password" : "text"}
        autoComplete={password ? "new-password" : "off"}
        value={String(form[key])}
        onChange={(e) => change(key, e.target.value as never)}
        placeholder={placeholder}
        disabled={working}
      />
    </Field>
  );
  return (
    <Dialog
      title={`${t(ingress ? "editControlSource" : "addControlSource")}${selected ? " · " + (preset?.displayName || t("customControlSource")) : ""}`}
      onClose={onClose}
      headerless={!ingress}
      width={!selected ? 480 : undefined}
      busy={working}
      footer={
        selected && (
          <>
            {ingress && (
              <Button
                variant="danger"
                disabled={working}
                onClick={() => void remove()}
              >
                {t("remove")}
              </Button>
            )}
            <span className="spacer" />
            <DialogClose asChild>
              <Button disabled={working}>{t("cancel")}</Button>
            </DialogClose>
            <Button
              variant="primary"
              busy={working}
              onClick={() => void save()}
            >
              {t("save")}
            </Button>
          </>
        )
      }
    >
      {!selected ? (
        <div className="source-choices">
          {[
            ...curatedSources.map((p) => ({
              value: p.id,
              label: p.displayName,
            })),
            { value: "custom", label: t("customControlSource") },
          ].map((option) => (
            <Button
              key={option.value}
              variant="ghost"
              onClick={() => choose(option.value)}
            >
              <SourceIcon
                platform={option.value}
                add={option.value === "custom"}
              />
              <span>{option.label}</span>
            </Button>
          ))}
        </div>
      ) : (
        <form
          className="form"
          ref={formRef}
          onSubmit={(e) => {
            e.preventDefault();
            void save();
          }}
          noValidate
        >
          {https &&
            auth === "bearer" &&
            preset &&
            !preset.supportedAuth.includes("bearer") && (
              <Notice tone="warning">{t("presetAuthMismatch")}</Notice>
            )}
          <Field
            id="ingress-name"
            label={t("sourceName")}
            error={errors.name}
            help={
              preset?.docs[0] && (
                <Button
                  variant="ghost"
                  onClick={() =>
                    void openUrl(preset.docs[0]!).catch((e) =>
                      setError(String(e)),
                    )
                  }
                >
                  {t("officialSetup")}
                </Button>
              )
            }
          >
            <Input
              id="ingress-name"
              value={name}
              onChange={(e) => {
                setName(e.target.value);
                setErrors((old) => ({ ...old, name: "" }));
              }}
              aria-invalid={!!errors.name}
              aria-describedby={errors.name ? "ingress-name-error" : undefined}
              disabled={working}
            />
          </Field>
          {selected === "custom" && (
            <Field
              id="ingress-source"
              label={t("controlSourceId")}
              error={errors.source}
            >
              <Input
                id="ingress-source"
                value={source}
                onChange={(e) => setSource(e.target.value)}
                aria-invalid={!!errors.source}
                aria-describedby={
                  errors.source ? "ingress-source-error" : undefined
                }
                disabled={working}
              />
            </Field>
          )}
          {allowTunnel && (
            <Field label={t("connectionMethod")}>
              <SingleChoice
                value={form.connectionMode}
                onChange={(value) =>
                  change(
                    "connectionMode",
                    value as ConnectionForm["connectionMode"],
                  )
                }
                label={t("connectionMethod")}
                disabled={working}
                options={[
                  { value: "tunnel", label: "OpenAI Secure Tunnel" },
                  { value: "https", label: "HTTPS MCP" },
                ]}
              />
            </Field>
          )}
          {!https ? (
            <>
              {textField(
                "tunnelId",
                "Tunnel ID",
                false,
                "tunnel_…",
                "https://platform.openai.com/settings/organization/tunnels",
              )}
              {textField(
                "apiKey",
                "Runtime API Key",
                true,
                ingress?.config.hasApiKey
                  ? t("savedLeaveBlankToKeep")
                  : t("pasteRuntimeKey"),
                "https://platform.openai.com/settings/organization/api-keys",
              )}
            </>
          ) : (
            <>
              <Field
                label={t("provider") + (allowTunnel ? "" : " · HTTPS MCP")}
              >
                <SingleChoice
                  value={form.httpsProvider}
                  onChange={(value) =>
                    change(
                      "httpsProvider",
                      value as ConnectionForm["httpsProvider"],
                    )
                  }
                  label={t("provider")}
                  disabled={working}
                  options={Object.entries(providers).map(([value, p]) => ({
                    value,
                    label: value === "custom" ? t("customDomain") : p.label,
                  }))}
                />
              </Field>
              {provider.mode && provider.modes.length > 1 && (
                <Field label={t("domainMode")}>
                  <SingleChoice
                    value={form[provider.mode]}
                    onChange={(value) =>
                      change(provider.mode!, value as "named" | "quick")
                    }
                    label={t("domainMode")}
                    disabled={working}
                    options={provider.modes.map((value) => ({
                      value,
                      label: t(
                        value === "named" ? "fixedDomain" : "temporaryDomain",
                      ),
                    }))}
                  />
                </Field>
              )}
              {needsCredential(form) &&
                provider.credential &&
                textField(
                  provider.credential,
                  provider.credentialLabel,
                  true,
                  credentialSaved(ingress?.config, provider.credential)
                    ? t("savedLeaveBlankToKeep")
                    : t("getToken"),
                  provider.help,
                )}
              {fixedDomain(form) &&
                textField("domain", t("domain"), false, "mcp.example.com")}
              <Field label={t("authentication")}>
                <SingleChoice
                  value={auth}
                  onChange={setAuth}
                  label={t("authentication")}
                  disabled={working}
                  options={[
                    { value: "none", label: t("authNone") },
                    { value: "bearer", label: "Bearer" },
                    { value: "oauth", label: "OAuth" },
                  ]}
                />
              </Field>
            </>
          )}
          <ToolPolicyField
            value={toolPolicy}
            onChange={setToolPolicy}
            disabled={working}
          />
          {error && <Notice>{displayMessage(error)}</Notice>}
        </form>
      )}
    </Dialog>
  );
}
