// ui/components/OAuthGrants.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue';
import { NAlert, NButton, NCard, NEmpty, NSpin, NTooltip } from 'naive-ui';
import { CircleHelp } from '@lucide/vue';
import { api } from '../composables/useConnector';
import { t } from '../i18n';
const props = defineProps<{ ingressId: string; running: boolean; disabled?: boolean }>();
const emit = defineEmits<{ busy: [value: boolean] }>();
interface Pending { id: string; clientName: string; redirectUri: string; status: 'pending' | 'waiting' | 'expired'; }
interface Grant { id: string; clientName: string; }
const grants = ref<Grant[]>([]), pending = ref<Pending[]>([]);
const error = ref(''), busy = ref(false);
let timer: ReturnType<typeof setTimeout> | undefined, disposed = false, revision = 0;
async function refresh(afterAction = false) {
  if (busy.value && !afterAction) return;
  if (!props.running) { grants.value = []; pending.value = []; error.value = ''; return; }
  const version = revision;
  try {
    const result = await api<{ grants: Grant[]; pending: Pending[] }>(`ingress/${props.ingressId}/oauth`);
    if (disposed || version !== revision || !props.running) return;
    grants.value = result.grants; pending.value = result.pending; error.value = '';
  } catch (e) { if (!disposed && version === revision) error.value = e instanceof Error ? e.message : String(e); }
}
async function poll() {
  await refresh();
  if (!disposed) timer = setTimeout(poll, 3000);
}
async function action(route: string, body: object) {
  if (busy.value || props.disabled || !props.running) return;
  revision++; busy.value = true; emit('busy', true); error.value = '';
  try {
    await api(`ingress/${props.ingressId}/oauth/${route}`, 'POST', body);
    await refresh(true);
    return true;
  } catch (e) { if (!disposed) error.value = e instanceof Error ? e.message : String(e); return false; }
  finally { busy.value = false; emit('busy', false); }
}
function sourceDomain(request: Pending) {
  try { return new URL(request.redirectUri).hostname; } catch { return ''; }
}
async function approve(request: Pending) {
  if (busy.value || props.disabled || !props.running) return;
  request.status = 'waiting';
  if (!await action('decision', { id: request.id, allow: true })) request.status = 'pending';
}
function deny(request: Pending) {
  void action('decision', { id: request.id, allow: false });
}
onMounted(() => { void poll(); });
onUnmounted(() => { disposed = true; clearTimeout(timer); emit('busy', false); });
</script>
<template>
  <section class="oauth-grants">
    <h3 class="oauth-heading"><span>OAuth</span><NTooltip><template #trigger><NButton text class="oauth-help-button" :aria-label="t('oauthConnectHint')"><template #icon><CircleHelp :size="12"/></template></NButton></template><span class="oauth-help">{{t('oauthConnectHint')}}</span></NTooltip></h3>
    <NCard v-for="request in pending" :key="request.id" class="oauth-request" size="small">
      <template #header>
        <div class="oauth-request-title"><span>{{request.clientName}}</span><small>{{sourceDomain(request)}}</small></div>
      </template>
      <template #header-extra><NButton size="small" type="error" :disabled="busy || disabled || !running" @click="deny(request)">{{t('oauthDeny')}}</NButton></template>
      <div class="oauth-decision">
      <NSpin v-if="request.status === 'waiting'" size="small"/>
      <NAlert v-else-if="request.status === 'expired'" type="error" :show-icon="false">{{t('oauthWaitExpired')}}</NAlert>
      <NButton v-else type="primary" :disabled="busy || disabled || !running" @click="approve(request)">{{t('oauthAllow')}}</NButton>
      <p v-if="request.status === 'waiting'" class="oauth-caption">{{t('oauthWaiting')}}</p>
      </div>
    </NCard>
    <div v-for="grant in grants" :key="grant.id" class="oauth-grant"><span>{{grant.clientName}}</span><NButton size="small" :disabled="busy || disabled" @click="action('revoke', { id: grant.id })">{{t('oauthRevoke')}}</NButton></div>
    <NEmpty v-if="!grants.length && !pending.length && !error" :description="t('oauthNoGrants')"/>
    <NAlert v-if="error" :show-icon="false" type="error">{{error}}</NAlert>
  </section>
</template>
<style scoped>
.oauth-grants{width:100%;margin-bottom:16px}.oauth-grants h3{font-size:13px;font-weight:500}.oauth-heading{display:flex;align-items:center;gap:6px}.oauth-help-button{width:16px;height:16px}.oauth-help{display:block;max-width:320px}.oauth-grant{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:8px 0}.oauth-grant span{min-width:0;overflow-wrap:anywhere}.oauth-grant small{display:block;color:var(--muted)}
.oauth-decision{display:flex;flex-direction:column;align-items:center;padding:14px 0 18px;overflow-x:auto}.oauth-caption{margin:12px 0 0;color:var(--muted);font-size:14px;text-align:center}.oauth-request{margin-bottom:12px}.oauth-request-title{display:flex;align-items:baseline;flex-wrap:wrap;gap:4px 8px;padding-right:12px;font-size:14px;overflow-wrap:anywhere}.oauth-request-title small{font-size:12px;font-weight:400;color:var(--muted)}
</style>

// ui/components/OAuthGrants.tsx
import { useEffect, useRef, useState } from "react";
import { api } from "../api";
import { t } from "../i18n";
import { useInterval } from "../state/hooks";
import { Button, Empty, Loading, Notice, IconButton } from "./ui";
import { CircleHelp } from "lucide-react";
type Pending = {
  id: string;
  clientName: string;
  redirectUri: string;
  status: "pending" | "waiting" | "expired";
};
type Grant = { id: string; clientName: string };
export default function OAuthGrants({
  ingressId,
  running,
  disabled,
  onBusy,
}: {
  ingressId: string;
  running: boolean;
  disabled?: boolean;
  onBusy: (value: boolean) => void;
}) {
  const [grants, setGrants] = useState<Grant[]>([]),
    [pending, setPending] = useState<Pending[]>([]),
    [error, setError] = useState(""),
    [busy, setBusy] = useState(false);
  const revision = useRef(0);
  const alive = useRef(true);
  useEffect(() => {
    alive.current = true;
    return () => {
      alive.current = false;
      revision.current++;
    };
  }, []);
  async function refresh(afterAction = false) {
    if (busy && !afterAction) return;
    if (!running) {
      setGrants([]);
      setPending([]);
      setError("");
      return;
    }
    const version = revision.current;
    try {
      const result = await api<{ grants: Grant[]; pending: Pending[] }>(
        `ingress/${ingressId}/oauth`,
      );
      if (alive.current && version === revision.current) {
        setGrants(result.grants);
        setPending(result.pending);
        setError("");
      }
    } catch (e) {
      if (alive.current && version === revision.current) setError(String(e));
    }
  }
  useInterval(() => void refresh(), 3000, true);
  useEffect(() => {
    void refresh();
  }, [running]);
  async function action(route: string, body: object) {
    if (busy || disabled || !running) return;
    revision.current++;
    setBusy(true);
    onBusy(true);
    setError("");
    try {
      await api(`ingress/${ingressId}/oauth/${route}`, "POST", body);
      await refresh(true);
    } catch (e) {
      setError(String(e));
    } finally {
      setBusy(false);
      onBusy(false);
    }
  }
  return (
    <section className="oauth-grants">
      <div className="actions">
        <h3>OAuth</h3>
        <IconButton icon={CircleHelp} label={t("oauthConnectHint")} />
      </div>
      {pending.map((request) => (
        <div className="oauth-request" key={request.id}>
          <div>
            <strong>{request.clientName}</strong>
            <p className="muted small">
              {(() => {
                try {
                  return new URL(request.redirectUri).hostname;
                } catch {
                  return "";
                }
              })()}
            </p>
          </div>
          <div className="actions">
            {request.status === "waiting" ? (
              <Loading label={t("oauthWaiting")} />
            ) : request.status === "expired" ? (
              <Notice>{t("oauthWaitExpired")}</Notice>
            ) : (
              <Button
                variant="primary"
                disabled={busy || disabled || !running}
                onClick={() =>
                  void action("decision", { id: request.id, allow: true })
                }
              >
                {t("oauthAllow")}
              </Button>
            )}
            <Button
              variant="danger"
              disabled={busy || disabled || !running}
              onClick={() =>
                void action("decision", { id: request.id, allow: false })
              }
            >
              {t("oauthDeny")}
            </Button>
          </div>
        </div>
      ))}
      {grants.map((grant) => (
        <div className="settings-row" key={grant.id}>
          <span>{grant.clientName}</span>
          <Button
            disabled={busy || disabled || !running}
            onClick={() => void action("revoke", { id: grant.id })}
          >
            {t("oauthRevoke")}
          </Button>
        </div>
      ))}
      {!grants.length && !pending.length && !error && (
        <Empty>{t("oauthNoGrants")}</Empty>
      )}
      {error && <Notice>{error}</Notice>}
    </section>
  );
}
