// ui/components/SettingsPage.tsx
import { useEffect, useState } from "react";
import { Monitor, Sun, Moon } from "lucide-react";
import { t, language, languageOptions, setLanguage } from "../i18n";
import { theme, themeColor, themeColors, type Theme } from "../theme";
import { api } from "../api";
import { isDesktop } from "../platform";
import { connector, run, notify, refreshConnector } from "../state/connector";
import { useInterval } from "../state/hooks";
import type { Service } from "../state/types";
import { Button, Group, Row, Switch, SingleChoice, Input, Field } from "./ui";
import { AppUpdate } from "./AppUpdate";
export default function SettingsPage() {
  const { status, busy } = connector.use();
  const currentTheme = theme.use(),
    color = themeColor.use(),
    currentLanguage = language.use();
  const [proxyMode, setProxyMode] = useState(
      status?.config.proxyMode || "system",
    ),
    [proxyUrl, setProxyUrl] = useState(status?.config.proxyUrl || ""),
    [proxyError, setProxyError] = useState("");
  const [appearance, setAppearance] = useState({
      showMenuBar: true,
      showDock: true,
    }),
    [appearanceReady, setAppearanceReady] = useState(false),
    [service, setService] = useState<Service>(),
    [notifications, setNotifications] = useState(
      localStorage.getItem("notifications") !== "off",
    );
  const mac = isDesktop && navigator.platform.toLowerCase().includes("mac");
  useEffect(() => {
    if (mac)
      void api<typeof appearance>("appearance")
        .then((value) => {
          setAppearance(value);
          setAppearanceReady(true);
        })
        .catch((e) => notify(String(e), true));
  }, [mac]);
  useInterval(
    () => {
      void api<Service>("service")
        .then(setService)
        .catch(() => {});
    },
    5000,
    true,
  );
  async function saveProxy(mode = proxyMode) {
    setProxyError("");
    if (mode === "custom") {
      try {
        const url = new URL(proxyUrl.trim());
        if (!["http:", "https:"].includes(url.protocol)) throw new Error();
      } catch {
        setProxyError(t("validProxyUrl"));
        return;
      }
    }
    await run("network", async () => {
      await api("network", "PUT", {
        proxyMode: mode,
        proxyUrl: mode === "custom" ? proxyUrl.trim() : "",
      });
      await refreshConnector();
      const current = connector.get().status;
      setProxyMode(current?.config.proxyMode || "system");
      setProxyUrl(current?.config.proxyUrl || "");
      notify(
        t(
          current?.connection?.running
            ? "proxySavedReconnectToApplyNewDownloadsUse"
            : "proxySettingsSaved",
        ),
      );
    });
  }
  async function saveTask(patch: {
    enabled?: boolean;
    autoOpenCodex?: boolean;
  }) {
    await run("task-settings", async () => {
      await api("task-settings", "PUT", patch);
      await refreshConnector();
    });
  }
  return (
    <div className="settings-page">
      <Group title={t("behavior")}>
        <Row
          title={t("automaticallyOpenCodexTasks")}
          description={t("whenDisabledNewTasksRunInTheBackground")}
        >
          <Switch
            label={t("automaticallyOpenCodexTasks")}
            checked={status?.autoOpenCodex !== false}
            disabled={!!busy || !status}
            onChange={(value) => void saveTask({ autoOpenCodex: value })}
          />
        </Row>
        <Row
          title={t("taskApprovalMode")}
          description={t(
            status?.taskApprovalEnabled
              ? "askForConfirmationByDefaultTheCloudCan"
              : "submitTaskRequestsImmediately",
          )}
        >
          <Switch
            label={t("taskApprovalMode")}
            checked={!!status?.taskApprovalEnabled}
            disabled={!!busy || !status}
            onChange={(value) => void saveTask({ enabled: value })}
          />
        </Row>
      </Group>
      <Group title={t("general")}>
        <Row
          title={t("connectAtSystemSignIn")}
          description={t("theConnectionKeepsRunningAfterTheWindowCloses")}
        >
          <Switch
            label={t("connectAtSystemSignIn")}
            checked={!!service?.enabled}
            disabled={!!busy || !service?.supported}
            onChange={(enabled) =>
              void run("startup", async () =>
                setService(await api<Service>("service", "POST", { enabled })),
              )
            }
          />
        </Row>
        {isDesktop && (
          <Row title={t("connectionNotifications")}>
            <Switch
              label={t("connectionNotifications")}
              checked={notifications}
              onChange={(value) => {
                setNotifications(value);
                localStorage.setItem("notifications", value ? "on" : "off");
              }}
            />
          </Row>
        )}
        <Row title={t("language")}>
          <SingleChoice
            value={currentLanguage}
            onChange={setLanguage}
            label={t("language")}
            options={languageOptions}
          />
        </Row>
        <Row title={t("appearance")}>
          <SingleChoice
            value={currentTheme}
            onChange={(value) => theme.set(value as Theme)}
            label={t("appearance")}
            options={[
              { value: "system", label: t("system"), icon: Monitor },
              { value: "light", label: t("light"), icon: Sun },
              { value: "dark", label: t("dark"), icon: Moon },
            ]}
          />
        </Row>
        <Row title={t("themeColor")}>
          <SingleChoice
            swatches
            value={color}
            onChange={(value) =>
              themeColor.set(value as keyof typeof themeColors)
            }
            label={t("themeColor")}
            options={Object.entries(themeColors).map(([value, color]) => ({
              value,
              label: t(color.label),
              color: color.light,
            }))}
          />
        </Row>
        {mac && (
          <Row title={t("showAppIn")}>
            <SingleChoice
              value={
                appearance.showMenuBar
                  ? appearance.showDock
                    ? "all"
                    : "menu"
                  : "dock"
              }
              disabled={!!busy || !appearanceReady}
              label={t("showAppIn")}
              onChange={(position) =>
                void run("appearance", async () =>
                  setAppearance(
                    await api<typeof appearance>("appearance", "PUT", {
                      showMenuBar: position !== "dock",
                      showDock: position !== "menu",
                    }),
                  ),
                )
              }
              options={[
                { value: "all", label: t("all") },
                { value: "menu", label: t("menuBarOnly") },
                { value: "dock", label: t("dockOnly") },
              ]}
            />
          </Row>
        )}
      </Group>
      <Group title={t("network")}>
        <Row
          title={t("proxy")}
          description={t("useTheSystemProxyOrAProxyJust")}
        >
          <SingleChoice
            value={proxyMode}
            disabled={!!busy}
            label={t("proxyMode")}
            onChange={(value) => {
              setProxyMode(value as typeof proxyMode);
              setProxyError("");
              if (value !== "custom") void saveProxy(value as typeof proxyMode);
            }}
            options={[
              { value: "system", label: t("systemProxy") },
              { value: "direct", label: t("noProxy") },
              { value: "custom", label: t("custom") },
            ]}
          />
        </Row>
        {proxyMode === "custom" && (
          <Field id="proxy-url" label={t("proxyUrl")} error={proxyError}>
            <form
              className="actions"
              onSubmit={(e) => {
                e.preventDefault();
                void saveProxy();
              }}
            >
              <Input
                id="proxy-url"
                value={proxyUrl}
                onChange={(e) => setProxyUrl(e.target.value)}
                placeholder="http://127.0.0.1:7890"
                aria-invalid={!!proxyError}
                aria-describedby={proxyError ? "proxy-url-error" : undefined}
                disabled={!!busy}
              />
              <Button type="submit" variant="primary" disabled={!!busy}>
                {t("save")}
              </Button>
            </form>
          </Field>
        )}
      </Group>
      <AppUpdate />
    </div>
  );
}

// ui/components/SettingsPage.vue
<script setup lang="ts">
import { t, language, languageOptions, setLanguage } from '../i18n';
import { NButton, NSwitch, NInput } from 'naive-ui';
import SingleChoice from './SingleChoice.vue';
import { theme } from '../theme';
import { Monitor, Sun, Moon } from '@lucide/vue';
import { useIntervalFn } from '@vueuse/core';
import { computed, onMounted, ref } from 'vue';
import { api, useConnector, type Service } from '../composables/useConnector';
import { isDesktop } from '../platform';
import AppUpdate from './AppUpdate.vue';
import SettingsGroup from './SettingsGroup.vue';
import SettingsRow from './SettingsRow.vue';
import '../settings.css';
const { status, busy, run, refresh, notify } = useConnector();
const proxyMode = ref(status.value?.config.proxyMode || 'system');
const proxyUrl = ref(status.value?.config.proxyUrl || '');
async function saveProxy() {
  if (proxyMode.value==='custom') {
    try { const url=new URL(proxyUrl.value.trim()); if(!['http:','https:'].includes(url.protocol)) throw new Error(); }
    catch { throw new Error(t('validProxyUrl')); }
  }
  await api('network', 'PUT', { proxyMode: proxyMode.value, proxyUrl: proxyMode.value === 'custom' ? proxyUrl.value.trim() : '' });
  await refresh();
  proxyUrl.value = status.value?.config.proxyUrl || '';
  notify(status.value?.connection?.running ? t('proxySavedReconnectToApplyNewDownloadsUse') : t('proxySettingsSaved'));
}
async function changeProxy() {
  if (proxyMode.value === 'custom') return;
  await run('network', saveProxy);
  proxyMode.value = status.value?.config.proxyMode || 'system';
}
const mac = navigator.platform.toLowerCase().includes('mac');
const appearance = ref({ showMenuBar: true, showDock: true });
const appearanceReady = ref(false);
onMounted(async () => {
  if (!mac || !isDesktop) return;
  try {
    appearance.value = await api<typeof appearance.value>('appearance');
    appearanceReady.value = true;
  } catch (error) { notify(error instanceof Error ? error.message : String(error), true); }
});
const displayPosition = computed(() => appearance.value.showMenuBar ? (appearance.value.showDock ? 'all' : 'menu') : 'dock');
async function setAppearance(position: 'all' | 'menu' | 'dock') {
  const next = { showMenuBar: position !== 'dock', showDock: position !== 'menu' };
  await run('appearance', async () => {
    appearance.value = await api<typeof appearance.value>('appearance', 'PUT', next);
  });
}
const service = ref<Service>();
const notifications = ref(localStorage.getItem('notifications') !== 'off');
const refreshService = () => api<Service>('service').then(value => service.value = value).catch(() => {});
onMounted(refreshService);
useIntervalFn(refreshService, 5000);
async function startup(enabled: boolean) {
  await run('startup', async () => { service.value = await api<Service>('service', 'POST', { enabled }); });
}
function preferences() {
  localStorage.setItem('notifications', notifications.value ? 'on' : 'off');
}
async function setAutoOpen(autoOpenCodex: boolean) {
  await run('task-settings', async () => { await api('task-settings', 'PUT', { autoOpenCodex }); await refresh(); });
}
async function setApproval(enabled: boolean) {
  await run('task-settings', async () => { await api('task-settings', 'PUT', { enabled }); await refresh(); });
}
</script>
<template>
  <div class="settings-preferences">


    <SettingsGroup :title="t('tasks')">
      <SettingsRow :title="t('automaticallyOpenCodexTasks')" :description="t('whenDisabledNewTasksRunInTheBackground')" control-id="settings-auto-open">
        <NSwitch id="settings-auto-open" :aria-label="t('automaticallyOpenCodexTasks')"  :value="status?.autoOpenCodex !== false" :disabled="!!busy || !status" @update:value="setAutoOpen" />
      </SettingsRow>
      <SettingsRow :title="t('taskApprovalMode')" :description="status?.taskApprovalEnabled ? t('askForConfirmationByDefaultTheCloudCan') : t('submitTaskRequestsImmediately')" control-id="settings-approval">
        <NSwitch id="settings-approval" :aria-label="t('taskApprovalMode')"  :value="!!status?.taskApprovalEnabled" :disabled="!!busy || !status" @update:value="setApproval" />
      </SettingsRow>
    </SettingsGroup>

    <SettingsGroup :title="t('general')">
      <SettingsRow :title="t('connectAtSystemSignIn')" :description="t('theConnectionKeepsRunningAfterTheWindowCloses')" control-id="settings-startup">
        <NSwitch id="settings-startup" :aria-label="t('connectAtSystemSignIn')"  :value="service?.enabled" :disabled="!!busy || !service?.supported" @update:value="startup" />
      </SettingsRow>
      <SettingsRow v-if="isDesktop" :title="t('connectionNotifications')" :description="t('notifyMeWhenTheConnectionNeedsAttention')" control-id="settings-notifications">
        <NSwitch id="settings-notifications" :aria-label="t('connectionNotifications')" v-model:value="notifications"  @update:value="preferences" />
      </SettingsRow>
      <SettingsRow :title="t('language')">
        <SingleChoice :value="language" :label="t('language')" :options="languageOptions" @update:value="setLanguage"/>
      </SettingsRow>
      <SettingsRow :title="t('appearance')">
        <SingleChoice v-model:value="theme" :label="t('appearance')" @update:value="preferences" :options="[{value:'system',label:t('system'),icon:Monitor},{value:'light',label:t('light'),icon:Sun},{value:'dark',label:t('dark'),icon:Moon}]"/>
      </SettingsRow>
      <SettingsRow v-if="mac" :title="t('showAppIn')">
        <SingleChoice :value="displayPosition" :disabled="!!busy || !appearanceReady" :label="t('showAppIn')" @update:value="setAppearance" :options="[{value:'all',label:t('all')},{value:'menu',label:t('menuBarOnly')},{value:'dock',label:t('dockOnly')}] as const"/>
      </SettingsRow>
    </SettingsGroup>

    <SettingsGroup :title="t('network')">
      <SettingsRow :title="t('proxy')" :description="t('useTheSystemProxyOrAProxyJust')">
        <SingleChoice v-model:value="proxyMode" :disabled="!!busy" :label="t('proxyMode')" @update:value="changeProxy" :options="[{value:'system',label:t('systemProxy')},{value:'direct',label:t('noProxy')},{value:'custom',label:t('custom')}] as const"/>
      </SettingsRow>
      <SettingsRow v-if="proxyMode === 'custom'" :title="t('proxyUrl')" :description="t('supportsHttpHttpsProxiesReconnectAfterSavingTo')" control-id="settings-proxy-url">
        <form class="proxy-form" @submit.prevent="run('network', saveProxy)">
          <NInput :input-props="{id:'settings-proxy-url','aria-label':t('proxyUrl')}" v-model:value="proxyUrl" placeholder="http://127.0.0.1:7890" :disabled="!!busy" />
          <NButton attr-type="submit" :disabled="!!busy" type="primary">{{ t('save') }}</NButton>
        </form>
      </SettingsRow>
    </SettingsGroup>

    <AppUpdate />
    <footer class="settings-version">Local Connector <span v-if="status">{{status.version}}</span></footer>
  </div>
</template>

<style scoped>
.proxy-form { display: flex; gap: 8px; max-width: 100%; }
.proxy-form .n-input { width: 220px; min-width: 0; }
@media (max-width: 600px) { .proxy-form .n-input { width: 190px; } }
</style>
