// ui/components/TasksPage.vue
<script setup lang="ts">
import { displayMessage } from '../messages';
import { t, locale } from '../i18n';
import ElasticPanel from './ElasticPanel.vue';
import { computed, ref, watch } from 'vue';
import { useClipboard, useIntervalFn, useResizeObserver } from '@vueuse/core';
import { api, useConnector } from '../composables/useConnector';
import type { TaskRecord, TaskRuntime } from '../composables/useTasks';
const props = defineProps<{ records: TaskRecord[]; error: string }>();
const emit = defineEmits<{ refresh: [] }>();
const { busy, run } = useConnector();
const runtimes = ref<Record<string, TaskRuntime>>({});
const { copy, copied } = useClipboard();
const runtimeLabels = computed<Record<string, string>>(() => ({ waiting:t('awaitingInteraction'), active:t('running'), idle:t('idle'), systemError:t('runtimeError') }));
const decisions = computed<Record<string, string>>(() => ({pending:t('awaitingConfirmation'), automatic:t('automaticExecution'), approved:t('approved'), bypass:t('bypassed'), reject:t('rejected')}));
const kinds = computed<Record<string, string>>(() => ({create:t('createTask'),send:t('sendInput'),interrupt:t('interruptTask'),native:t('manageTask')}));
const idOf = (r: TaskRecord) => r.threadId || r.task.threadId;
const projectOf = (r: TaskRecord) => r.task.project || r.task.directory || (idOf(r) && runtimes.value[idOf(r)!]?.project) || '';
const titleOf = (r: TaskRecord) => r.task.title || (idOf(r) && runtimes.value[idOf(r)!]?.title) || r.task.prompt.split('\n')[0]?.slice(0, 90) || kinds.value[r.task.kind] || t('taskRequest');
const time = (s: string) => new Date(s).toLocaleString(locale.value, { hour12: false });
const groups = computed(() => {
  const result = new Map<string, TaskRecord[]>();
  for (const r of props.records) {
    const key = idOf(r) || r.requestId;
    const list = result.get(key) || [];
    list.push(r); result.set(key, list);
  }
  return [...result].map(([id, records]) => ({ id, records, first: records.find(r => r.task.kind === 'create') || records[records.length - 1]!, latest: records[0]! })).sort((a,b) => b.first.createdAt.localeCompare(a.first.createdAt));
});
const visible = computed(() => groups.value);
watch(() => props.records, records => {
  for (const r of records) {
    const id = idOf(r);
    if (id && r.runtime && !runtimes.value[id]) runtimes.value[id] = r.runtime;
  }
}, { immediate:true });
const projectName = (r: TaskRecord) => projectOf(r).replace(/[\\/]+$/, '').split(/[\\/]/).pop() || projectOf(r);
const createdTime = (s: string) => new Date(s).toLocaleString(locale.value, { year:'2-digit', month:'2-digit', day:'2-digit', hour:'2-digit', minute:'2-digit', hour12:false });
function stateOf(g: (typeof groups.value)[number]) {
  const runtime = runtimes.value[g.id];
  if (runtime?.archived) return t('archived');
  if (!runtime || runtime.stale) return '';
  return runtimeLabels.value[runtime.runtimeStatus] || '';
}
let checking = false;
async function refreshRuntime() {
  if (checking) return;
  checking = true;
  const ids = visible.value.map(g => idOf(g.first)).filter((id): id is string => !!id);
  try {
    // Keep owner snapshot reads bounded; failed refreshes retain the last observed state.
    for (let i = 0; i < ids.length; i += 4) await Promise.all(ids.slice(i, i + 4).map(async id => {
      try { runtimes.value[id] = await api<TaskRuntime>(`tasks/runtime/${encodeURIComponent(id)}`); }
      catch { const old = runtimes.value[id]; runtimes.value[id] = old ? { ...old, stale: true } : { runtimeStatus:'unknown', observedAt:'', stale:true }; }
    }));
  } finally { checking = false; }
}
watch(() => visible.value.map(g => g.id).join(','), refreshRuntime, { immediate:true });
useIntervalFn(refreshRuntime, 10000);
async function decide(r: TaskRecord, action: string) {
  await run('task-decision', async () => {
    await api('tasks/decision', 'POST', { requestId:r.requestId, action });
    emit('refresh');
  });
}
async function copyPrompt(prompt: string) {
  actionError.value = '';
  try { await copy(prompt); } catch { actionError.value = t('copyFailedSelectAndCopyTheTextManually'); }
}
const actionError = ref('');
const openingTask = ref(false);
async function openTask(id: string) {
  if (openingTask.value) return;
  actionError.value = '';
  openingTask.value = true;
  try { await api('tasks/open', 'POST', { threadId: id }); }
  catch { if (selectedId.value === id) actionError.value = t('unableToOpenCodexMakeSureCodexIs'); }
  finally { openingTask.value = false; }
}
const selectedId = ref<string>();
const selected = computed(() => groups.value.find(g => g.id === selectedId.value));
const detailOpen = ref(false);
const origin = ref({x:0,y:0,size:1,height:1});
const cards = ref<HTMLElement[]>([]);
useResizeObserver(cards, entries => {
  for (const { target } of entries) {
    const card = target as HTMLElement;
    card.parentElement!.style.gridRowEnd = `span ${Math.ceil(card.offsetHeight + 22)}`;
  }
});
function focusCard(id: string, event: MouseEvent) {
  actionError.value = '';
  const rect = (event.currentTarget as HTMLElement).getBoundingClientRect();
  origin.value = { x: rect.x, y: rect.y, size: rect.width, height: rect.height };
  selectedId.value = id;
  detailOpen.value = true;
}
</script>
<template>
  <section class="tasks-page" :aria-label="t('cloudTasks')">
    <p v-if="error" class="status-banner warning" role="alert">{{displayMessage(error)}}</p>
    <div class="task-grid">
      <div v-for="g in visible" :key="g.id" class="task-cell"><button ref="cards" class="task-document" aria-haspopup="dialog" @click="focusCard(g.id,$event)">
        <span class="task-document-heading"><strong class="task-document-title">{{titleOf(g.first)}}</strong><span v-if="g.first.task.model" class="task-tag">{{g.first.task.model}}</span><span v-if="g.first.task.effort" class="task-tag">{{g.first.task.effort}}</span></span>
        <time :datetime="g.first.createdAt">{{createdTime(g.first.createdAt)}}</time>
        <span v-if="g.first.task.prompt" class="task-document-preview">{{g.first.task.prompt}}</span>
        <span class="task-document-bottom"><span v-if="projectOf(g.first)" class="task-document-project" :title="projectOf(g.first)">{{projectName(g.first)}}</span><span v-if="stateOf(g)" class="task-document-state">{{stateOf(g)}}</span></span>
      </button></div>
    </div>
    <ElasticPanel v-if="selected" :show="detailOpen" :origin="origin" :title="titleOf(selected.first)" :width="720" :busy="!!busy || openingTask" @close="detailOpen=false" @closed="selectedId=undefined">
      <div class="task-document-heading"><span v-if="selected.first.task.model" class="task-tag">{{selected.first.task.model}}</span><span v-if="selected.first.task.effort" class="task-tag">{{selected.first.task.effort}}</span><time>{{createdTime(selected.first.createdAt)}}</time></div>
          <div class="task-focus-content">
          <p v-if="selected.first.executionOwner === 'connector'" class="hint">{{ t('connectorRunsThisTaskInTheBackgroundDisconnecting') }}</p>
        <section v-for="r in [...selected.records].reverse()" :key="r.requestId" class="task-entry">
          <div class="task-entry-heading"><strong>{{kinds[r.task.kind] || t('manageTask')}}</strong><span v-if="r.task.model" class="task-tag">{{r.task.model}}</span><span v-if="r.task.effort" class="task-tag">{{r.task.effort}}</span><time>{{time(r.createdAt)}}</time><button v-if="r.task.prompt" class="text-button" @click="copyPrompt(r.task.prompt)">{{copied?t('copied'):t('copyPrompt')}}</button></div>
          <pre v-if="r.task.prompt" class="task-prompt">{{r.task.prompt}}</pre>
          <div v-if="decisions[r.approval.decision]" class="task-entry-meta"><span v-if="decisions[r.approval.decision]">{{decisions[r.approval.decision]}} · {{r.approval.source==='local'?t('local'):t('cloud')}}</span></div>
          <p v-if="r.error?.message" class="status-banner warning">{{displayMessage(r.error.message)}}</p>
          <div v-if="r.state==='awaiting-approval'" class="task-entry-actions"><button class="primary" :disabled="!!busy" @click="decide(r,'approve')">{{ t('approveAndSubmit') }}</button><button :disabled="!!busy" @click="decide(r,'reject')">{{ t('reject') }}</button></div>
        </section>
          </div>
          <p v-if="actionError" class="status-banner warning" role="alert">{{displayMessage(actionError)}}</p>
          <template v-if="projectOf(selected.first) || stateOf(selected) || idOf(selected.first)" #footer><div class="task-focus-footer"><span v-if="projectOf(selected.first)" class="task-document-project" :title="projectOf(selected.first)">{{projectName(selected.first)}}</span><span v-if="stateOf(selected)" class="task-document-state">{{stateOf(selected)}}</span><button v-if="idOf(selected.first) && !runtimes[selected.id]?.archived" class="text-button" :disabled="openingTask" @click="openTask(selected.id)">{{openingTask ? t('opening') : t('openInCodex')}}</button></div></template>
    </ElasticPanel>
    <p v-if="!visible.length && !error" class="empty">{{ t('noTasksYet') }}</p>
  </section>
</template>

// ui/components/TasksPage.tsx
import { useEffect, useLayoutEffect, useMemo, useRef, useState } from "react";
import { ExternalLink, Copy } from "lucide-react";
import { t, locale } from "../i18n";
import { api } from "../api";
import { copyText } from "../platform";
import { displayMessage } from "../messages";
import { connector, run, notify } from "../state/connector";
import {
  tasks,
  refreshTasks,
  type TaskRecord,
  type TaskRuntime,
} from "../state/tasks";
import { useInterval } from "../state/hooks";
import { Button, Empty, IconButton, Loading, Notice, Dialog } from "./ui";
const idOf = (r: TaskRecord) => r.threadId || r.task.threadId;
export default function TasksPage() {
  const { records, error, loading } = tasks.use(),
    { busy } = connector.use();
  const [runtimes, setRuntimes] = useState<Record<string, TaskRuntime>>({}),
    [selectedId, setSelectedId] = useState<string>(),
    [opening, setOpening] = useState(false),
    [actionError, setActionError] = useState("");
  const groups = useMemo(() => {
    const result = new Map<string, TaskRecord[]>();
    for (const r of records) {
      const key = idOf(r) || r.requestId;
      result.set(key, [...(result.get(key) || []), r]);
    }
    return [...result]
      .map(([id, records]) => ({
        id,
        records,
        first: records.find((r) => r.task.kind === "create") || records.at(-1)!,
      }))
      .sort((a, b) => b.first.createdAt.localeCompare(a.first.createdAt));
  }, [records]);
  const runtime = (r: TaskRecord) => runtimes[idOf(r) || ""] || r.runtime;
  const titleOf = (r: TaskRecord) =>
    r.task.title ||
    runtime(r)?.title ||
    r.task.prompt.split("\n")[0]?.slice(0, 90) ||
    t("taskRequest");
  const projectOf = (r: TaskRecord) =>
    r.task.project || r.task.directory || runtime(r)?.project || "";
  const projectName = (r: TaskRecord) =>
    projectOf(r)
      .replace(/[\\/]+$/, "")
      .split(/[\\/]/)
      .pop() || "";
  const stateOf = (group: (typeof groups)[number]) =>
    group.records.some((r) => r.state === "awaiting-approval")
      ? "awaitingConfirmation"
      : runtime(group.first)?.archived
        ? "archived"
        : !runtime(group.first) || runtime(group.first)?.stale
          ? "unknown"
          : {
              waiting: "awaitingInteraction",
              active: "running",
              idle: "idle",
              systemError: "runtimeError",
            }[runtime(group.first)!.runtimeStatus] || "unknown";
  const visible = groups;
  const selected = groups.find((g) => g.id === selectedId);
  const reading = useRef(false);
  const alive = useRef(true);
  useEffect(() => {
    alive.current = true;
    return () => {
      alive.current = false;
    };
  }, []);
  async function refreshRuntime() {
    if (reading.current) return;
    reading.current = true;
    const ids = groups
      .map((g) => idOf(g.first))
      .filter((id): id is string => !!id);
    for (let i = 0; i < ids.length; i += 4)
      await Promise.all(
        ids.slice(i, i + 4).map(async (id) => {
          try {
            const next = await api<TaskRuntime>(
              `tasks/runtime/${encodeURIComponent(id)}`,
            );
            if (alive.current) setRuntimes((old) => ({ ...old, [id]: next }));
          } catch {
            if (alive.current)
              setRuntimes((old) => ({
                ...old,
                [id]: {
                  ...(old[id] || { runtimeStatus: "unknown", observedAt: "" }),
                  stale: true,
                },
              }));
          }
        }),
      );
    reading.current = false;
  }
  const ids = groups.map((g) => g.id).join(",");
  useEffect(() => {
    void refreshRuntime();
  }, [ids]);
  useInterval(() => void refreshRuntime(), 10000);
  function closeDetail() {
    const id = selectedId;
    setSelectedId(undefined);
    requestAnimationFrame(() =>
      document
        .querySelector<HTMLButtonElement>(
          `[data-task-id="${CSS.escape(id || "")}"]`,
        )
        ?.focus(),
    );
  }
  const grid = useRef<HTMLDivElement>(null);
  useLayoutEffect(() => {
    let frame = 0;
    const cards = [
      ...(grid.current?.querySelectorAll<HTMLElement>(".task-document") ?? []),
    ];
    const observer = new ResizeObserver(() => {
      cancelAnimationFrame(frame);
      frame = requestAnimationFrame(() => {
        const heights = cards.map((card) => Math.ceil(card.offsetHeight + 22));
        cards.forEach((card, index) => {
          card.parentElement!.style.gridRowEnd = `span ${heights[index]}`;
        });
      });
    });
    cards.forEach((node) => observer.observe(node));
    return () => {
      cancelAnimationFrame(frame);
      observer.disconnect();
    };
  }, [ids]);
  const time = (value: string) =>
    new Date(value).toLocaleString(locale.get(), {
      year: "2-digit",
      month: "2-digit",
      day: "2-digit",
      hour: "2-digit",
      minute: "2-digit",
      hour12: false,
    });
  const detail = selected && (
    <Dialog
      title={titleOf(selected.first)}
      width={720}
      busy={!!busy || opening}
      onClose={closeDetail}
      footer={
        <div className="task-focus-footer">
          <span
            className="task-document-project"
            title={projectOf(selected.first)}
          >
            {projectName(selected.first)}
          </span>
          <span className="task-document-state">{t(stateOf(selected))}</span>
          {idOf(selected.first) && !runtime(selected.first)?.archived && (
            <IconButton
              icon={ExternalLink}
              label={t("openInCodex")}
              busy={opening}
              onClick={() => {
                setOpening(true);
                setActionError("");
                void api("tasks/open", "POST", { threadId: selected.id })
                  .catch(() =>
                    setActionError(t("unableToOpenCodexMakeSureCodexIs")),
                  )
                  .finally(() => setOpening(false));
              }}
            />
          )}
        </div>
      }
    >
      <div className="task-document-heading">
        {selected.first.task.model && (
          <span className="task-tag">{selected.first.task.model}</span>
        )}
        {selected.first.task.effort && (
          <span className="task-tag">{selected.first.task.effort}</span>
        )}
        <time>{time(selected.first.createdAt)}</time>
      </div>
      <div className="task-focus-content">
        {selected.first.executionOwner === "connector" && (
          <p className="muted small">
            {t("connectorRunsThisTaskInTheBackgroundDisconnecting")}
          </p>
        )}
        {[...selected.records].reverse().map((r) => (
          <section className="task-entry" key={r.requestId}>
            <header>
              <strong>
                {t(
                  {
                    create: "createTask",
                    send: "sendInput",
                    interrupt: "interruptTask",
                    native: "manageTask",
                  }[r.task.kind] || "manageTask",
                )}
              </strong>
              <time>{time(r.createdAt)}</time>
              {r.task.prompt && (
                <IconButton
                  icon={Copy}
                  label={t("copyPrompt")}
                  onClick={() =>
                    void copyText(r.task.prompt)
                      .then(() => notify(t("copied")))
                      .catch(() =>
                        setActionError(
                          t("copyFailedSelectAndCopyTheTextManually"),
                        ),
                      )
                  }
                />
              )}
            </header>
            <pre className="task-prompt">{r.task.prompt}</pre>
            <p className="muted small">
              {t(
                {
                  pending: "awaitingConfirmation",
                  automatic: "automaticExecution",
                  approved: "approved",
                  bypass: "bypassed",
                  reject: "rejected",
                }[r.approval.decision] || r.approval.decision,
              )}{" "}
              · {t(r.approval.source === "local" ? "local" : "cloud")}
              {r.task.model ? ` · ${r.task.model}` : ""}
              {r.task.effort ? ` · ${r.task.effort}` : ""}
            </p>
            {r.error?.message && (
              <Notice>{displayMessage(r.error.message)}</Notice>
            )}
            {r.state === "awaiting-approval" && (
              <div className="actions">
                {["approve", "reject"].map((action) => (
                  <Button
                    key={action}
                    variant={action === "approve" ? "primary" : "secondary"}
                    disabled={!!busy}
                    onClick={() =>
                      void run("task-decision", async () => {
                        await api("tasks/decision", "POST", {
                          requestId: r.requestId,
                          action,
                        });
                        await refreshTasks();
                      })
                    }
                  >
                    {t(action === "approve" ? "approveAndSubmit" : "reject")}
                  </Button>
                ))}
              </div>
            )}
          </section>
        ))}
        {actionError && <Notice>{actionError}</Notice>}
      </div>
    </Dialog>
  );
  return (
    <section className="tasks-page">
      {error && (
        <Notice
          action={
            <Button onClick={() => void refreshTasks()}>{t("retry")}</Button>
          }
        >
          {displayMessage(error)}
        </Notice>
      )}
      {loading ? (
        <Loading />
      ) : (
        <div ref={grid} className="task-grid">
          {visible.map((g) => (
            <div className="task-cell" key={g.id}>
              <button
                type="button"
                className="task-document"
                data-task-id={g.id}
                aria-haspopup="dialog"
                onClick={() => {
                  setSelectedId(g.id);
                  setActionError("");
                }}
              >
                <span className="task-document-heading">
                  <strong className="task-document-title">
                    {titleOf(g.first)}
                  </strong>
                  {g.first.task.model && (
                    <span className="task-tag">{g.first.task.model}</span>
                  )}
                  {g.first.task.effort && (
                    <span className="task-tag">{g.first.task.effort}</span>
                  )}
                </span>
                <time dateTime={g.first.createdAt}>
                  {time(g.first.createdAt)}
                </time>
                {g.first.task.prompt && (
                  <span className="task-document-preview">
                    {g.first.task.prompt}
                  </span>
                )}
                <span className="task-document-bottom">
                  {projectOf(g.first) && (
                    <span
                      className="task-document-project"
                      title={projectOf(g.first)}
                    >
                      {projectName(g.first)}
                    </span>
                  )}
                  <span className="task-document-state">{t(stateOf(g))}</span>
                </span>
              </button>
            </div>
          ))}
        </div>
      )}
      {detail}
      {!loading && !visible.length && !error && (
        <Empty>{t(groups.length ? "noMatchingTasks" : "noTasksYet")}</Empty>
      )}
    </section>
  );
}
