// ui/tray-panel/TrayPanel.vue
<script setup lang="ts">
import {computed,onMounted,onUnmounted,ref} from 'vue';
import {NAlert,NButton,NEmpty,NSpin} from 'naive-ui';
import {ChevronRight} from '@lucide/vue';
import QuotaBubble from '../subscriptions/QuotaBubble.vue';
import {useSubscriptions} from '../subscriptions/useSubscriptions';
import {api} from '../api';
import {isDesktop} from '../platform';
import {t} from '../i18n';
import {brandIcon} from '../subscriptions/presentation';
import {copyShareCard} from './shareCard';
const subscriptions=useSubscriptions();
const side=ref<'left'|'right'>('left'), dismissKey=ref(0),busy=ref(false),error=ref('');
const connection=ref(false),version=ref(''),copied=ref(false);
const content=ref<HTMLElement>(),footer=ref<HTMLElement>();
let resizeObserver:ResizeObserver|undefined,resizeFrame=0,lastHeight=0;
function resizePanel(){
  cancelAnimationFrame(resizeFrame);
  resizeFrame=requestAnimationFrame(async()=>{
    if(!content.value||!footer.value)return;
    const height=Math.ceil(content.value.getBoundingClientRect().height+footer.value.getBoundingClientRect().height+2);
    if(!isDesktop||height===lastHeight)return;
    lastHeight=height;
    try{const {invoke}=await import('@tauri-apps/api/core');await invoke('tray_panel_resize',{height});}
    catch(e){lastHeight=0;error.value=String(e);}
  });
}
const providerCards=new Map<string,HTMLElement>();
let copyTimer:ReturnType<typeof setTimeout>|undefined;
function registerCard(id:string,el:unknown){if(el instanceof HTMLElement)providerCards.set(id,el);else providerCards.delete(id);}
const providers=computed(()=>subscriptions.snapshot.value?.settings.enabled?subscriptions.snapshot.value.providers.filter(p=>p.selected&&p.eligible):[]);
async function nativeAction(action:string){
  if(isDesktop){const {invoke}=await import('@tauri-apps/api/core');await invoke('tray_action',{action});}
  else if(['overview','settings','tasks','logs'].includes(action))window.location.href='/';
}
async function readStatus(){
  const status=await api<{connection:{running:boolean};version:string}>('status');
  connection.value=status.connection.running;version.value=status.version;
}
async function select(key:string){
  error.value='';
  try{await nativeAction(key);}catch(e){error.value=String(e);}
}
async function share(id:string){
  error.value='';copied.value=false;busy.value=true;
  try{
    const card=providerCards.get(id),provider=providers.value.find(p=>p.providerId===id);
    if(!card||!provider)throw new Error(t('trayEmpty'));
    await copyShareCard(card,brandIcon(provider.agentId));
    copied.value=true;clearTimeout(copyTimer);copyTimer=setTimeout(()=>copied.value=false,4000);
  }catch(e){error.value=String(e);}finally{busy.value=false;}
}
async function openOptions(event:MouseEvent){
  if(!isDesktop||busy.value)return;
  error.value='';dismissKey.value++;
  const rect=(event.currentTarget as HTMLElement).getBoundingClientRect();
  let menu:import('@tauri-apps/api/menu').Menu|undefined;
  try{
    await readStatus();
    const {Menu}=await import('@tauri-apps/api/menu');
    const {LogicalPosition}=await import('@tauri-apps/api/dpi');
    menu=await Menu.new({items:[
      {id:'status',text:`${t('trayConnectionStatus')}：${t(connection.value?'trayConnected':'trayDisconnected')}`,action:()=>void select('overview')},
      {id:'settings',text:t('traySettings'),accelerator:'CmdOrCtrl+,',action:()=>void select('settings')},
      {item:'Separator'},
      {id:'share',text:t('trayShareScreenshot'),enabled:providers.value.length>0,items:providers.value.map(p=>({id:`share:${p.providerId}`,text:p.name,action:()=>void share(p.providerId)}))},
      {id:'updates',text:t('checkForUpdates')+'…',action:()=>void select('updates')},
      {item:'Separator'},
      {item:{About:{name:'Local Connector',version:version.value,license:'MIT',website:'https://github.com/whzxc/chatgpt-local-connector'}},text:t('trayAbout')},
      {id:'quit',text:t('trayQuit'),accelerator:'CmdOrCtrl+Q',action:()=>void select('quit')},
    ]});
    await nativeAction('menu-open');
    await menu.popup(new LogicalPosition(rect.left,rect.top));
  }catch(e){error.value=String(e);}finally{
    await nativeAction('menu-close').catch(e=>error.value=String(e));
    await menu?.close();
  }
}
async function opened(){dismissKey.value++;await Promise.all([subscriptions.read(),readStatus().catch(e=>error.value=String(e))]);}
function dismiss(){void nativeAction('hide');}
function keydown(e:KeyboardEvent){if(e.key==='Escape'){e.preventDefault();dismiss();}}
let off:(()=>void)|undefined,disposed=false;
onMounted(async()=>{resizeObserver=new ResizeObserver(resizePanel);if(content.value)resizeObserver.observe(content.value);if(footer.value)resizeObserver.observe(footer.value);resizePanel();document.addEventListener('keydown',keydown);if(isDesktop){const {listen}=await import('@tauri-apps/api/event');const stop=await listen<{side:'left'|'right'}>('tray-panel:open',e=>{side.value=e.payload.side;void opened();});if(disposed)stop();else off=stop;}await readStatus().catch(e=>error.value=String(e));});
onUnmounted(()=>{resizeObserver?.disconnect();cancelAnimationFrame(resizeFrame);clearTimeout(copyTimer);disposed=true;off?.();document.removeEventListener('keydown',keydown);});
</script>
<template>
  <div class="tray-surface" @mousedown.self="dismiss">
    <section class="tray-card" :class="side" :aria-label="t('trayUsage')">
      <div class="tray-scroll" @scroll="dismissKey++">
        <div ref="content" class="tray-content">
        <NAlert v-if="error || subscriptions.error.value" type="error" :show-icon="false">{{error || subscriptions.error.value}}</NAlert>
        <NAlert v-if="copied" type="success" :show-icon="false" role="status">{{t('trayScreenshotCopied')}}</NAlert>
        <NSpin v-if="!subscriptions.snapshot.value && !subscriptions.error.value" size="small"/>
        <div v-for="provider in providers" :key="provider.providerId" :ref="el=>registerCard(provider.providerId,el)" class="provider-card"><QuotaBubble :provider="provider" embedded :external-detail="provider.providerId" :detail-placement="side" :dismiss-key="dismissKey"/></div>
        <NEmpty v-if="subscriptions.snapshot.value&&!providers.length" :description="t('trayEmpty')"><template #extra><NButton size="small" @click="select('settings')">{{t('traySettings')}}</NButton></template></NEmpty>
        </div>
      </div>
      <footer ref="footer"><span class="app-version">Local Connector {{version}}</span><NButton text size="small" class="connection-menu" :loading="busy" :disabled="!isDesktop" :aria-label="`${t(connection?'trayConnected':'trayDisconnected')} · ${t('trayOptions')}`" aria-haspopup="menu" @click="openOptions"><span>{{t(connection?'trayConnected':'trayDisconnected')}}</span><ChevronRight :size="12" aria-hidden="true"/></NButton></footer>
    </section>
  </div>
</template>
<style scoped>
.tray-surface{position:fixed;inset:0;color:var(--ink)}
.tray-card{position:absolute;top:0;max-height:100%;width:380px;max-width:100%;box-sizing:border-box;display:flex;flex-direction:column;background:var(--surface);border:1px solid var(--line);border-radius:22px;overflow:hidden}.tray-card.left{right:0}.tray-card.right{left:0}
.tray-scroll{min-height:0;overflow:auto;scrollbar-width:thin}.tray-content{padding:14px;display:flex;flex-direction:column;gap:14px}.provider-card{background:var(--soft);border-radius:18px;padding:14px;flex:none}footer{padding:8px 14px;min-height:22px;gap:12px;display:flex;justify-content:space-between;align-items:center;border-top:1px solid var(--line);flex:none;font-size:11px;color:var(--muted)}.app-version{white-space:nowrap}.connection-menu{flex:none;font-size:11px;color:var(--muted);gap:4px}
</style>

// ui/tray-panel/TrayPanel.tsx
import { useEffect, useLayoutEffect, useRef, useState } from "react";
import { ChevronRight } from "lucide-react";
import { api } from "../api";
import { t, locale } from "../i18n";
import { isDesktop } from "../platform";
import { subscriptions, readSubscriptions } from "../state/subscriptions";
import type { Page } from "../state/navigation";
import QuotaBubble from "../subscriptions/QuotaBubble";
import { brandIcon } from "../subscriptions/presentation";
import { copyShareCard } from "./shareCard";
import { Button, Empty, Icon, Loading, Menu, Notice } from "../components/ui";
export default function TrayPanel({
  embedded = false,
  onNavigate,
}: {
  embedded?: boolean;
  onNavigate?: (page: Page) => void;
}) {
  locale.use();
  const { snapshot, error: subscriptionError } = subscriptions.use();
  const providers = snapshot?.settings.enabled
    ? snapshot.providers.filter((p) => p.selected && p.eligible)
    : [];
  const [side, setSide] = useState<"left" | "right">("left"),
    [error, setError] = useState(""),
    [version, setVersion] = useState(""),
    [connection, setConnection] = useState(false),
    [busy, setBusy] = useState(false),
    [copied, setCopied] = useState(false),
    [dismissKey, setDismissKey] = useState(0);
  const content = useRef<HTMLDivElement>(null),
    footer = useRef<HTMLElement>(null),
    cards = useRef(new Map<string, HTMLElement>());
  async function action(action: string) {
    if (isDesktop && !embedded) {
      const { invoke } = await import("@tauri-apps/api/core");
      await invoke("tray_action", { action });
    } else if (["overview", "settings", "tasks", "logs"].includes(action)) {
      if (onNavigate) onNavigate(action as Page);
      else window.location.href = "/";
    }
  }
  async function select(key: string) {
    setError("");
    try {
      await action(key);
    } catch (e) {
      setError(String(e));
    }
  }
  async function readStatus() {
    const status = await api<{
      connection?: { running: boolean };
      version: string;
    }>("status");
    setConnection(!!status.connection?.running);
    setVersion(status.version);
  }
  async function share(id: string) {
    setError("");
    setCopied(false);
    setBusy(true);
    try {
      const card = cards.current.get(id),
        provider = providers.find((p) => p.providerId === id);
      if (!card || !provider) throw new Error(t("trayEmpty"));
      await copyShareCard(card, brandIcon(provider.agentId));
      setCopied(true);
    } catch (e) {
      setError(String(e));
    } finally {
      setBusy(false);
    }
  }
  useEffect(() => {
    if (!copied) return;
    const timer = setTimeout(() => setCopied(false), 4000);
    return () => clearTimeout(timer);
  }, [copied]);
  async function openOptions(event: React.MouseEvent<HTMLButtonElement>) {
    if (!isDesktop || embedded || busy) return;
    const rect = event.currentTarget.getBoundingClientRect();
    setError("");
    setDismissKey((k) => k + 1);
    let menu: import("@tauri-apps/api/menu").Menu | undefined;
    try {
      await readStatus();
      const [{ Menu }, { LogicalPosition }] = await Promise.all([
        import("@tauri-apps/api/menu"),
        import("@tauri-apps/api/dpi"),
      ]);
      menu = await Menu.new({
        items: [
          {
            id: "status",
            text: `${t("trayConnectionStatus")}：${t(connection ? "trayConnected" : "trayDisconnected")}`,
            action: () => void select("overview"),
          },
          {
            id: "settings",
            text: t("traySettings"),
            accelerator: "CmdOrCtrl+,",
            action: () => void select("settings"),
          },
          { item: "Separator" },
          {
            id: "share",
            text: t("trayShareScreenshot"),
            enabled: providers.length > 0,
            items: providers.map((p) => ({
              id: `share:${p.providerId}`,
              text: p.name,
              action: () => void share(p.providerId),
            })),
          },
          {
            id: "updates",
            text: t("checkForUpdates") + "…",
            action: () => void select("updates"),
          },
          { item: "Separator" },
          {
            item: {
              About: {
                name: "Local Connector",
                version,
                license: "MIT",
                website: "https://github.com/whzxc/chatgpt-local-connector",
              },
            },
            text: t("trayAbout"),
          },
          {
            id: "quit",
            text: t("trayQuit"),
            accelerator: "CmdOrCtrl+Q",
            action: () => void select("quit"),
          },
        ],
      });
      await action("menu-open");
      await menu.popup(new LogicalPosition(rect.left, rect.top));
    } catch (e) {
      setError(String(e));
    } finally {
      await action("menu-close").catch((e) => setError(String(e)));
      await menu?.close();
    }
  }
  useEffect(() => {
    void readStatus().catch((e) => setError(String(e)));
    if (!isDesktop || embedded) return;
    let stopped = false,
      off: (() => void) | undefined;
    void import("@tauri-apps/api/event").then(async ({ listen }) => {
      const dispose = await listen<{ side: "left" | "right" }>(
        "tray-panel:open",
        (e) => {
          setSide(e.payload.side);
          setDismissKey((k) => k + 1);
          void readSubscriptions();
          void readStatus().catch((e) => setError(String(e)));
        },
      );
      if (stopped) dispose();
      else off = dispose;
    });
    const key = (e: KeyboardEvent) => {
      if (
        e.key === "Escape" &&
        !document.querySelector("[data-radix-popper-content-wrapper]")
      ) {
        e.preventDefault();
        void select("hide");
      }
    };
    document.addEventListener("keydown", key);
    return () => {
      stopped = true;
      off?.();
      document.removeEventListener("keydown", key);
    };
  }, [embedded]);
  useLayoutEffect(() => {
    if (!isDesktop || embedded || !content.current || !footer.current) return;
    let frame = 0,
      lastHeight = 0;
    const resize = () => {
      cancelAnimationFrame(frame);
      frame = requestAnimationFrame(() => {
        const height = Math.ceil(
          content.current!.getBoundingClientRect().height +
            footer.current!.getBoundingClientRect().height +
            2,
        );
        if (height === lastHeight) return;
        lastHeight = height;
        void import("@tauri-apps/api/core")
          .then(({ invoke }) => invoke("tray_panel_resize", { height }))
          .catch((e) => {
            lastHeight = 0;
            setError(String(e));
          });
      });
    };
    const observer = new ResizeObserver(resize);
    observer.observe(content.current);
    observer.observe(footer.current);
    resize();
    return () => {
      observer.disconnect();
      cancelAnimationFrame(frame);
    };
  }, [embedded]);
  const optionsButton = (
    <Button
      variant="ghost"
      className="tray-options"
      aria-label={t("trayOptions")}
      busy={busy}
    >
      {t(connection ? "trayConnected" : "trayDisconnected")}
      <Icon icon={ChevronRight} />
    </Button>
  );
  return (
    <div className={`tray-surface ${embedded ? "embedded" : ""}`}>
      <section className={`tray-card ${side}`} aria-label={t("trayUsage")}>
        <div
          className="tray-scroll"
          onScroll={() => setDismissKey((k) => k + 1)}
        >
          <div ref={content} className="tray-content">
            {(error || subscriptionError) && (
              <Notice>{error || subscriptionError}</Notice>
            )}
            {copied && (
              <Notice tone="success">{t("trayScreenshotCopied")}</Notice>
            )}
            {!snapshot && !subscriptionError && <Loading />}
            {providers.map((provider) => (
              <div
                key={provider.providerId}
                ref={(el) => {
                  if (el) cards.current.set(provider.providerId, el);
                  else cards.current.delete(provider.providerId);
                }}
                className="provider-card"
              >
                <QuotaBubble
                  key={`${provider.providerId}:${dismissKey}`}
                  provider={provider}
                  detailPlacement={side}
                />
              </div>
            ))}
            {snapshot && !providers.length && (
              <Empty
                action={
                  <Button onClick={() => void select("settings")}>
                    {t("traySettings")}
                  </Button>
                }
              >
                {t("trayEmpty")}
              </Empty>
            )}
          </div>
        </div>
        <footer ref={footer}>
          <span>Local Connector {version}</span>
          {isDesktop && !embedded ? (
            <Button
              variant="ghost"
              className="tray-options"
              busy={busy}
              aria-label={t("trayOptions")}
              onClick={(event) => void openOptions(event)}
            >
              {t(connection ? "trayConnected" : "trayDisconnected")}
              <Icon icon={ChevronRight} />
            </Button>
          ) : (
            <Menu
              label={t("trayOptions")}
              trigger={optionsButton}
              items={[
                {
                  label: t("traySettings"),
                  action: () => void select("settings"),
                },
                ...providers.map((p) => ({
                  label: `${t("trayShareScreenshot")} · ${p.name}`,
                  action: () => void share(p.providerId),
                  disabled: !isDesktop || busy,
                })),
              ]}
            />
          )}
        </footer>
      </section>
    </div>
  );
}
