// ui/subscriptions/QuotaBubble.tsx
import { useState } from "react";
import { RefreshCw, TriangleAlert, CircleAlert, Flame } from "lucide-react";
import { t } from "../i18n";
import { openUrl } from "../platform";
import { useNow } from "../state/hooks";
import { refreshSubscription } from "../state/subscriptions";
import { Button, IconButton, Icon, Progress } from "../components/ui";
import {
  quotaDisplay,
  resetDisplay,
  quotaLabel,
  quotaPercent,
  quotaValue,
  usagePeriods,
  usagePeriodLabels,
} from "./displayPreferences";
import { windowLabel, subscriptionLabel, isFiveHour } from "./labels";
import {
  brandIcon,
  quotaColor,
  resetText,
  preciseTime,
  errorLabels,
} from "./presentation";
import { quotaPace } from "./pace";
import { cycleEstimate } from "./cycleEstimate";
import { usageLink } from "./usageLinks";
import type { ProviderSnapshot } from "./types";
import UsageHistory from "./UsageHistory";
import "./bubble.css";
export default function QuotaBubble({
  provider,
  warningAt,
  rail = false,
  onPopover,
  detailPlacement = "left",
}: {
  provider: ProviderSnapshot;
  warningAt?: number;
  rail?: boolean;
  onPopover?: (points: [number, number][]) => void;
  detailPlacement?: "left" | "right" | "bottom";
}) {
  const now = useNow(),
    reset = resetDisplay.use(),
    periods = usagePeriods.use();
  quotaDisplay.use();
  const [requesting, setRequesting] = useState(false),
    [error, setError] = useState("");
  const usageUrl = usageLink(provider),
    notices: string[] = [];
  if (error) notices.push(error);
  if (provider.error)
    notices.push(
      provider.error.message ||
        t(errorLabels[provider.error.code] || "usageUnavailable"),
    );
  if (
    provider.history?.error &&
    provider.history.error !== "history-unavailable"
  )
    notices.push(provider.history.error);
  if (provider.pinUnavailable) notices.push(t("usagePinUnavailable"));
  if (provider.accountBlocked) notices.push(t("usageAccountBlocked"));
  if (provider.state === "stale") notices.push(t("usageStale"));
  for (const w of provider.windows)
    if (w.exhausted || provider.blockedPoolIds.includes(w.poolId))
      notices.push(`${windowLabel(w.label)}: ${t("usagePoolBlocked")}`);
  const timestamp = Date.parse(provider.observedAt ?? ""),
    age = Number.isFinite(timestamp)
      ? Math.max(0, Math.floor((now - timestamp) / 60000))
      : undefined;
  const ageText =
    age === undefined
      ? ""
      : age < 1
        ? "< 1m"
        : age < 60
          ? `${age}m`
          : age < 1440
            ? `${Math.floor(age / 60)}h`
            : `${Math.floor(age / 1440)}d`;
  async function refresh() {
    setRequesting(true);
    setError("");
    try {
      await refreshSubscription(provider.providerId);
    } catch (e) {
      setError(String(e));
    } finally {
      setRequesting(false);
    }
  }
  const tokens = new Intl.NumberFormat(undefined, {
      notation: "compact",
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    }),
    dollars = new Intl.NumberFormat(undefined, {
      style: "currency",
      currency: "USD",
      maximumFractionDigits: 2,
    });

  const readings = provider.windows.map((w) => ({
    w,
    pace: quotaPace(w, provider, now),
    estimate: cycleEstimate(w, provider, now),
  }));
  const hasError =
    !!error ||
    !!provider.accountBlocked ||
    (!!provider.error &&
      ![
        "no-subscription",
        "no-limits-reported",
        "unsupported-platform",
      ].includes(provider.error.code)) ||
    (!!provider.history?.error &&
      provider.history.error !== "history-unavailable");
  function detail(key: string) {
    const reading = readings.find((r) => "reading:" + r.w.id === key);
    if (key === "notices")
      return (
        <>
          {notices.map((notice, i) => (
            <div key={i}>{notice}</div>
          ))}
        </>
      );
    if (reading)
      return (
        <>
          {[reading.pace?.tooltip, ...(reading.estimate?.lines ?? [])]
            .filter(Boolean)
            .map((line, i) => (
              <div key={i}>{line}</div>
            ))}
        </>
      );
    if (key === "resets")
      return (
        <>
          {provider.resetCredits?.length
            ? provider.resetCredits.map((credit, index) => (
                <div className="history-period expiry-row" key={index}>
                  <span>
                    <span className="credit-number">{index + 1}</span>
                    {preciseTime(credit.expiresAt) || t("usageExpiryUnknown")}
                  </span>
                  <span>{resetText(credit.expiresAt, now)}</span>
                </div>
              ))
            : t("usageExpiryUnknown")}
        </>
      );
    const row = provider.history?.periods?.find((p) => p.id === key);
    if (!row) return null;
    return (
      <>
        <strong>{t(usagePeriodLabels[row.id])}</strong>
        {row.models?.length
          ? row.models.map((model) => (
              <div className="model-reading" key={model.model}>
                <div className="history-period">
                  <strong>{model.model}</strong>
                  <span className="model-share">
                    {row.tokens
                      ? Math.round((model.tokens / row.tokens) * 100)
                      : 0}
                    %
                  </span>
                </div>
                <Progress
                  label={model.model}
                  value={row.tokens ? (model.tokens / row.tokens) * 100 : 0}
                />
                <div className="history-period model-meta">
                  <span>
                    {model.estimatedUsd == null
                      ? "—"
                      : dollars.format(model.estimatedUsd)}
                  </span>
                  <span title={model.tokens.toLocaleString() + " tokens"}>
                    {tokens.format(model.tokens)} tokens
                  </span>
                </div>
              </div>
            ))
          : "-"}
      </>
    );
  }
  return (
    <div className={`quota-bubble ${rail ? "rail-quota" : "embedded"}`}>
      <UsageHistory
        rail={rail}
        side={detailPlacement}
        detail={detail}
        onBounds={onPopover}
      >
        {({ register, hover, focus, expanded, displayed }) => (
          <>
            <header>
              <span
                className="provider-logo"
                style={{
                  maskImage: `url(${JSON.stringify(brandIcon(provider.agentId))})`,
                }}
                aria-hidden="true"
              />
              <span className="subscription-heading">
                {usageUrl ? (
                  <a
                    className="subscription-link"
                    href={usageUrl}
                    draggable={false}
                    onClick={(e) => {
                      e.preventDefault();
                      void openUrl(usageUrl).catch((e) => setError(String(e)));
                    }}
                  >
                    {subscriptionLabel(provider)}
                  </a>
                ) : (
                  <strong>{subscriptionLabel(provider)}</strong>
                )}
                {provider.plan && provider.agentId !== "codex" && (
                  <span className="provider-plan">{provider.plan}</span>
                )}
                {notices.length > 0 && (
                  <span
                    ref={(node) => register("notices", node)}
                    onMouseEnter={() => hover("notices")}
                    onMouseLeave={() => hover("")}
                    onFocus={() => focus("notices")}
                    onBlur={() => focus("")}
                    tabIndex={0}
                    aria-expanded={expanded && displayed === "notices"}
                    className={`subscription-notice ${hasError ? "error" : ""}`}
                    role="img"
                    aria-label={notices.join(" · ")}
                  >
                    <Icon icon={hasError ? CircleAlert : TriangleAlert} />
                  </span>
                )}
              </span>
              <time
                className="refresh-age"
                title={preciseTime(provider.observedAt)}
              >
                {ageText}
                {ageText && ageText !== "< 1m" ? " ago" : ""}
              </time>
              <IconButton
                icon={RefreshCw}
                label={t("usageRefresh")}
                busy={requesting || provider.refreshing}
                disabled={!provider.eligible || !provider.selected}
                onClick={() => void refresh()}
              />
            </header>
            {readings.map(({ w, pace, estimate }) => {
              const key = "reading:" + w.id;
              return (
                <div key={w.id} className="bubble-reading">
                  <div className="reading-title">
                    <span>
                      {provider.providerId === "antigravity" && w.scope
                        ? `${w.scope} · `
                        : ""}
                      {windowLabel(w.label)}
                    </span>
                    {estimate && (
                      <span className="quota-estimate">
                        ≈ {estimate.amount}
                      </span>
                    )}
                    {w.id === provider.displayWindowId && (
                      <i role="img" aria-label={t("usageMainDisplay")} />
                    )}
                    {pace?.label && (
                      <Button
                        variant="ghost"
                        className="pace-warning"
                        ref={(node) => register(key, node)}
                        onMouseEnter={() => hover(key)}
                        onMouseLeave={() => hover("")}
                        onClick={() => focus(key)}
                        onFocus={() => focus(key)}
                        onBlur={() => focus("")}
                        aria-expanded={expanded && displayed === key}
                        aria-label={`${windowLabel(w.label)} · ${pace.label}`}
                      >
                        {pace.flame && <Icon icon={Flame} />} {pace.label}
                      </Button>
                    )}
                  </div>
                  <div
                    className="reading-track"
                    role="meter"
                    aria-label={`${windowLabel(w.label)} · ${quotaLabel()}`}
                    aria-valuenow={quotaValue(w)}
                    aria-valuemin={0}
                    aria-valuemax={100}
                  >
                    <div
                      style={{
                        width: `${quotaValue(w)}%`,
                        background:
                          pace?.color ?? quotaColor(w, provider, warningAt),
                      }}
                    />
                    {pace?.tick != null && (
                      <span
                        className="pace-tick"
                        style={{
                          left: `clamp(1px, ${pace.tick}%, calc(100% - 1px))`,
                        }}
                      />
                    )}
                  </div>
                  <div className="reading-meta">
                    <span>
                      {quotaLabel()} {quotaPercent(w)}
                    </span>
                    <span>
                      {reset === "time"
                        ? preciseTime(w.resetsAt) || "—"
                        : resetText(w.resetsAt, now, isFiveHour(w.label))}
                    </span>
                  </div>
                </div>
              );
            })}
            <div className="usage-history">
              {provider.availableResetCount != null && (
                <div className="history-period">
                  <span>{t("usageResetCount")}</span>
                  <Button
                    ref={(node) => {
                      register("resets", node);
                    }}
                    variant="ghost"
                    className="history-toggle"
                    onMouseEnter={() => hover("resets")}
                    onMouseLeave={() => hover("")}
                    onClick={() => focus("resets")}
                    onFocus={() => focus("resets")}
                    onBlur={() => focus("")}
                    aria-expanded={expanded && displayed === "resets"}
                  >
                    <span>
                      {t("usageResetCountValue", {
                        count: provider.availableResetCount,
                      })}
                    </span>
                  </Button>
                </div>
              )}
              {provider.history?.periods
                ?.filter((row) => periods.includes(row.id))
                .map((row) => (
                  <div className="history-period" key={row.id}>
                    <span>{t(usagePeriodLabels[row.id])}</span>
                    <Button
                      variant="ghost"
                      className="history-toggle"
                      ref={(node) => {
                        register(row.id, node);
                      }}
                      onMouseEnter={() => hover(row.id)}
                      onMouseLeave={() => hover("")}
                      onFocus={() => focus(row.id)}
                      onBlur={() => focus("")}
                      aria-expanded={expanded && displayed === row.id}
                      onClick={(e) => {
                        e.stopPropagation();
                        focus(row.id);
                      }}
                    >
                      {row.tokens
                        ? `${row.estimatedUsd == null ? "—" : dollars.format(row.estimatedUsd)} · ${tokens.format(row.tokens)} tokens`
                        : "-"}
                    </Button>
                  </div>
                ))}
            </div>
          </>
        )}
      </UsageHistory>
    </div>
  );
}

// ui/subscriptions/QuotaBubble.vue
<script setup lang="ts">
import {quotaPace} from './pace';
import {cycleEstimate} from './cycleEstimate';
import UsageHistory from './UsageHistory.vue';
import {ref,inject,onUnmounted,computed} from 'vue';
import {NButton,NText} from 'naive-ui';
import {RefreshCw,Flame,TriangleAlert,CircleAlert} from '@lucide/vue';
import {openUrl} from '../platform';
import {usageLink} from './usageLinks';
import {subscriptionRefreshKey} from './useSubscriptions';
import {t} from '../i18n';
import {type ProviderSnapshot} from './types';
import {quotaLabel,quotaPercent,quotaValue,resetDisplay} from './displayPreferences';
import {windowLabel,subscriptionLabel,isFiveHour} from './labels';
import {brandIcon,quotaColor,resetText,preciseTime,errorLabels} from './presentation';
const emit=defineEmits<{popover:[points:[number,number][]]}>();
const props=defineProps<{provider:ProviderSnapshot;warningAt?:number;embedded?:boolean;detailPlacement?:'left'|'right'}>();
const refreshSubscription=inject(subscriptionRefreshKey);
const usageUrl=computed(()=>usageLink(props.provider));
async function openUsage(){if(!usageUrl.value)return;try{await openUrl(usageUrl.value);}catch(error){refreshError.value=String(error);}}
const requesting=ref(false),refreshError=ref('');
async function refresh() {
  if (!refreshSubscription || requesting.value || props.provider.refreshing) return;
  requesting.value=true;refreshError.value='';
  try { await refreshSubscription(props.provider.providerId); }
  catch (error) { refreshError.value=String(error); }
  finally { requesting.value=false; }
}
const notices=computed(()=>{
  const p=props.provider, items:{message:string;error:boolean}[]=[];
  if(refreshError.value)items.push({message:refreshError.value,error:true});
  if(p.error)items.push({message:t(errorLabels[p.error.code]||'usageUnavailable'),error:!['no-subscription','no-limits-reported','unsupported-platform'].includes(p.error.code)});
  if(p.history?.error && p.history.error!=='history-unavailable')items.push({message:p.history.error,error:true});
  if(p.pinUnavailable)items.push({message:t('usagePinUnavailable'),error:false});
  if(p.accountBlocked)items.push({message:t('usageAccountBlocked'),error:true});
  for(const w of p.windows)if(w.exhausted||p.blockedPoolIds.includes(w.poolId))items.push({message:`${windowLabel(w.label)}：${t('usagePoolBlocked')}`,error:false});
  if(p.state==='stale')items.push({message:t('usageStale'),error:false});
  return items;
});
const hasError=computed(()=>notices.value.some(n=>n.error));
const details=computed(()=>[
  ...(notices.value.length?[{id:'notices',lines:notices.value.map(n=>n.message)}]:[]),
  ...readings.value.map(({w,pace,estimate})=>({id:'quota:'+w.id,lines:
    pace || estimate ? [pace?.tooltip,...(estimate?.lines??[])].filter((line):line is string=>!!line)
      : [windowLabel(w.label),`${quotaLabel()} ${quotaPercent(w)}`,preciseTime(w.resetsAt)].filter(Boolean)}))]);
const readings=computed(()=>props.provider.windows.map(w=>({w,pace:quotaPace(w,props.provider,now.value),estimate:cycleEstimate(w,props.provider,now.value)})));
const now=ref(Date.now());const timer=setInterval(()=>now.value=Date.now(),60000);onUnmounted(()=>clearInterval(timer));
const refreshAge=computed(()=>{
  const timestamp=Date.parse(props.provider.observedAt??'');
  if(!Number.isFinite(timestamp))return '';
  const minutes=Math.max(0,Math.floor((now.value-timestamp)/60000));
  if(minutes<1)return '< 1m';
  if(minutes<60)return `${minutes}m ago`;
  if(minutes<1440)return `${Math.floor(minutes/60)}h ago`;
  return `${Math.floor(minutes/1440)}d ago`;
});
</script>
<template>
  <div class="quota-bubble" :class="{embedded}">
    <UsageHistory :rail="!embedded" :detail-placement="detailPlacement" @popover="emit('popover',$event)" :history="provider.history" :reset-count="provider.availableResetCount" :reset-credits="provider.resetCredits" :now="now" :details="details" v-slot="{register,hover,focus,expanded,displayed}">
      <header>
        <span class="provider-logo" :style="{maskImage: `url(${JSON.stringify(brandIcon(provider.agentId))})`}" aria-hidden="true"/>
        <span class="subscription-heading">
          <NText v-if="usageUrl" tag="a" class="subscription-link" :href="usageUrl" target="_blank" rel="noopener noreferrer" :draggable="false" style="color:inherit" @click.stop.prevent="openUsage">{{subscriptionLabel(provider)}}</NText>
          <strong v-else>{{subscriptionLabel(provider)}}</strong>
          <span v-if="provider.plan && provider.agentId!=='codex'" class="provider-plan">{{provider.plan}}</span>
          <span v-if="notices.length" :ref="el=>register('notices',el)" @mouseenter="hover('notices')" @mouseleave="hover('')" @focus="focus('notices')" @blur="focus('')" tabindex="0" :aria-expanded="expanded&&displayed==='notices'" class="subscription-notice" :class="{error:hasError}" role="img" :aria-label="notices.map(n=>n.message).join(' · ')"><CircleAlert v-if="hasError" :size="14"/><TriangleAlert v-else :size="14"/></span>
        </span>
        <span v-if="refreshAge" class="refresh-age">{{refreshAge}}</span>
        <NButton v-if="refreshSubscription" class="quota-refresh" text size="small" style="color:var(--quota-muted,var(--rail-muted))" :loading="requesting || provider.refreshing" :disabled="requesting || provider.refreshing || !provider.eligible || !provider.selected" :aria-label="t('usageRefresh')" @click.stop="refresh"><template #icon><RefreshCw :size="14"/></template></NButton>
      </header>
      <div v-for="{w,pace,estimate} in readings" :key="w.id" class="bubble-reading" :ref="el=>register('quota:'+w.id,el)" @mouseenter="hover('quota:'+w.id)" @mouseleave="hover('')" :aria-expanded="expanded&&displayed==='quota:'+w.id" tabindex="0" @focus="focus('quota:'+w.id)" @blur="focus('')" :aria-label="[windowLabel(w.label),pace?.tooltip,...(estimate?.lines??[])].filter(Boolean).join(' · ')">
        <div class="reading-title">
          <span>{{provider.providerId==='antigravity' && w.scope ? w.scope+' · ' : ''}}{{windowLabel(w.label)}}</span>
          <span v-if="estimate" class="quota-estimate">≈ {{estimate.amount}}</span>
          <i v-if="w.id===provider.displayWindowId" role="img" :aria-label="t('usageMainDisplay')"/>
          <span v-if="pace?.label" class="pace-warning"><Flame v-if="pace.flame" :size="12" :color="pace.color"/>{{pace.label}}</span>
        </div>
        <div class="reading-track"><div :style="{width:`${quotaValue(w)}%`,background:pace?.color ?? quotaColor(w,provider,warningAt)}"/><span v-if="pace?.tick!=null" class="pace-tick" :style="{left:`clamp(1px, ${pace.tick}%, calc(100% - 1px))`}"/></div>
        <div class="reading-meta"><span>{{quotaLabel()}} {{quotaPercent(w)}}</span><span>{{resetDisplay==='time' ? preciseTime(w.resetsAt) || '—' : resetText(w.resetsAt,now,isFiveHour(w.label))}}</span></div>
      </div>
    </UsageHistory>
  </div>
</template>
<style scoped>
.quota-bubble{box-sizing:border-box;width:280px;padding:18px;display:flex;flex-direction:column;gap:14px;color:var(--quota-ink,var(--rail-ink));font-family:ui-rounded,'SF Pro Rounded',-apple-system,sans-serif}.quota-bubble header{display:flex;align-items:center;gap:7px;min-height:19px;line-height:19px;font-size:14px}.provider-logo{width:16px;height:16px;flex:none;background:currentColor;mask-size:contain;mask-repeat:no-repeat;mask-position:center}.quota-bubble header strong,.subscription-link{font-weight:600}.subscription-link{text-decoration:none;cursor:pointer}.subscription-link:hover{text-decoration:underline}.subscription-link:focus-visible{outline:2px solid currentColor;outline-offset:3px;border-radius:2px}.refresh-age{flex:none;white-space:nowrap;font-size:10px;font-weight:400;color:var(--quota-muted,var(--rail-muted));font-variant-numeric:tabular-nums}.quota-refresh{flex:none;width:20px;height:20px}.quota-bubble .provider-plan{max-width:76px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:11px;color:var(--quota-muted,var(--rail-muted))}.bubble-reading{display:flex;flex-direction:column;gap:7px;font-size:11.5px;line-height:14px;font-variant-numeric:tabular-nums}.reading-title{display:flex;flex-wrap:wrap;align-items:center;gap:6px;min-height:14px}.quota-estimate{white-space:nowrap;font-size:10.5px;color:var(--quota-muted,var(--rail-muted))}.reading-title i{flex:none;width:4px;height:4px;border-radius:50%;background:var(--quota-muted,var(--rail-muted))}.reading-track{height:6px;flex:none;background:var(--quota-track,var(--rail-track));border-radius:3px;position:relative}.reading-track div{height:100%;border-radius:3px}.reading-meta{display:flex;justify-content:space-between;gap:5px}.reading-meta>span:last-child{color:var(--quota-muted,var(--rail-muted));text-align:right}.quota-bubble p{margin:0;color:var(--quota-muted,var(--rail-muted));font-size:12px;line-height:17px}.subscription-heading{display:flex;align-items:center;gap:7px;min-width:0;margin-right:auto}.subscription-notice{display:inline-flex;align-items:center;flex:none;color:var(--usage-caution)}.subscription-notice.error{color:var(--usage-warning)}
.quota-bubble.embedded{width:100%;padding:0;--quota-ink:var(--ink);--quota-muted:var(--muted);--quota-track:var(--line)}
</style>

<style scoped>
.pace-warning{margin-left:auto;display:flex;align-items:center;gap:4px;color:var(--quota-muted,var(--rail-muted));white-space:nowrap}.reading-title>span:first-child{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.pace-tick{position:absolute;top:-2px;width:2px;height:10px;border-radius:1px;transform:translateX(-50%);background:var(--quota-muted,var(--rail-muted))}
</style>
