// ui/App.vue
<script setup lang="ts">
import { displayMessage } from './messages';
import { t } from './i18n';
import { computed, defineAsyncComponent, ref, watch, nextTick, onMounted, onUnmounted } from 'vue';
import { LayoutDashboard, Logs, Settings, Download, X, Maximize2, Minimize2 } from '@lucide/vue';
import { NButton } from 'naive-ui';
import { provideConnector } from './composables/useConnector';
import { isDesktop, notifyNative } from './platform';
import { startUpdateChecks, useAppUpdate } from './composables/useAppUpdate';
import AppUpdateDialog from './components/AppUpdateDialog.vue';
import { panelLayers } from './composables/panels';
const appUpdate = useAppUpdate();
let stopUpdateChecks = () => {};
onMounted(() => { stopUpdateChecks = startUpdateChecks(); });
onUnmounted(() => stopUpdateChecks());
import TasksPage from './components/TasksPage.vue';
import { useTasks } from './composables/useTasks';
const tasks = useTasks();
import RecordsPage from './components/RecordsPage.vue';
const SettingsPage = defineAsyncComponent(() => import('./components/SettingsPage.vue'));
import ChatGuide from './components/ChatGuide.vue';
import ConnectionOverview from './components/ConnectionOverview.vue';
const { status, feedback, notify } = provideConnector();
type Page = 'guide' | 'overview' | 'logs' | 'settings' | 'tasks';
const page = ref<Page>('overview');
const panelOpen = computed(() => panelLayers.value.length > 0);
const sheetWide = ref(false);
const workspace = ref<HTMLElement>();
watch(page, () => workspace.value?.scrollTo({ top: 0 }));
const mac = isDesktop && navigator.platform.toLowerCase().includes('mac');
const lastPage = ref<Page>('tasks');
async function navigate(next: Page) {
  if(next !== 'overview') { lastPage.value = next; sheetWide.value = false; }
  page.value = next;
  await nextTick();
  if(next === 'overview') document.querySelector<HTMLButtonElement>(`[data-page="${lastPage.value}"]`)?.focus();
  else document.querySelector<HTMLElement>('.capsule-title')?.focus();
}
function closePage(event: KeyboardEvent) {
  if(event.key === 'Escape' && page.value !== 'overview' && !panelOpen.value) {
    event.preventDefault(); void navigate('overview');
  }
}
const unlisteners: (() => void)[] = [];
onMounted(async () => {
  if (!isDesktop) return;
  const { listen } = await import('@tauri-apps/api/event');
  unlisteners.push(await listen<string>('navigate', event => { if (['overview','settings','logs','tasks'].includes(event.payload)) navigate(event.payload as Page); }));
  unlisteners.push(await listen<string>('connection-error', event => notify(event.payload, true)));
});
onUnmounted(() => unlisteners.forEach(stop => stop()));
watch(() => status.value?.core.appServer.state, (n,old) => { if(old && n==='error' && n!==old) void notifyNative(t('localConnectionError'),t('checkDiagnosticsInSettings')).catch(()=>{}); });
let toastTimer: ReturnType<typeof setTimeout>;
watch(() => feedback.value.text, text => { clearTimeout(toastTimer); if(text && !feedback.value.error) toastTimer=setTimeout(()=>feedback.value.text='',4500); });
onUnmounted(()=>clearTimeout(toastTimer));
</script>
<template>
  <div class="app-scene" :class="{desktop:isDesktop,mac,'sheet-wide':sheetWide}" @keydown="closePage">
    <div v-if="isDesktop" class="window-drag-strip" data-tauri-drag-region/>
    <main class="home-workspace" :inert="page!=='overview' || panelOpen">
      <ConnectionOverview/>
    </main>
    <div class="navigation-surface" :class="{expanded:page!=='overview'}" aria-hidden="true"/>
    <Transition name="capsule-page">
      <section v-if="page!=='overview'" class="page-sheet" :inert="panelOpen" :aria-label="page==='settings'?t('settings'):page==='tasks'?t('tasks'):t('records')">
        <main ref="workspace" class="workspace" :class="{'records-workspace':page==='logs'}">
          <ChatGuide v-if="page==='guide'" @done="navigate('overview')" @settings="navigate('settings')"/>
          <TasksPage v-else-if="page==='tasks'" :records="tasks.records.value" :error="tasks.error.value" @refresh="tasks.refresh"/>
          <RecordsPage v-else-if="page==='logs'"/>
          <SettingsPage v-else-if="status"/>
        </main>
        <NButton class="panel-width-toggle" quaternary circle :aria-label="t(sheetWide ? 'restorePanelWidth' : 'expandPanelWidth')" :title="t(sheetWide ? 'restorePanelWidth' : 'expandPanelWidth')" :aria-pressed="sheetWide" @click="sheetWide=!sheetWide"><template #icon><component :is="sheetWide ? Minimize2 : Maximize2" :size="20"/></template></NButton>
      </section>
    </Transition>
    <nav :inert="panelOpen" class="navigation-capsule" :class="{expanded:page!=='overview'}" :aria-label="t('mainNavigation')">
      <template v-if="page!=='overview'"><button class="capsule-close" :aria-label="t('backToHome')" :title="t('backToHome')" @click="navigate('overview')"><X aria-hidden="true"/></button><h1 class="capsule-title" tabindex="-1">{{page==='settings'?t('settings'):page==='tasks'?t('tasks'):page==='logs'?t('records'):t('home')}}</h1></template>
      <div class="capsule-icons" :inert="page!=='overview'" :aria-hidden="page!=='overview'">
        <button data-page="tasks" class="tasks-nav" :aria-label="t('tasks')" :title="t('tasks')" @click="navigate('tasks')"><LayoutDashboard aria-hidden="true"/><span v-if="tasks.pending.value.length" class="task-count">{{tasks.pending.value.length}}</span></button>
        <button data-page="logs" :aria-label="t('records')" :title="t('records')" @click="navigate('logs')"><Logs aria-hidden="true"/></button>
        <button data-page="settings" :aria-label="t('settings')" :title="t('settings')" @click="navigate('settings')"><Settings aria-hidden="true"/></button>
      </div>
    </nav>
    <button v-if="appUpdate.available.value" class="update-shortcut" :aria-label="t('updateToValue', { version: appUpdate.update.value?.version })" :title="t('newVersionValueViewUpdate', { version: appUpdate.update.value?.version })" aria-haspopup="dialog" @click="appUpdate.showUpdate"><Download aria-hidden="true"/></button>
    <div v-if="feedback.text && feedback.error" class="status-banner warning app-feedback" role="alert"><span>{{displayMessage(feedback.text)}}</span><button class="ghost banner-dismiss" :aria-label="t('dismissMessage')" @click="feedback.text=''"><X aria-hidden="true"/></button></div>
    <AppUpdateDialog/>
    <div v-if="feedback.text && !feedback.error" class="message" role="status">{{displayMessage(feedback.text)}}<button :aria-label="t('dismissMessage')" @click="feedback.text=''"><X aria-hidden="true"/></button></div>
  </div>
</template>

// ui/App.tsx
import {
  lazy,
  Suspense,
  useEffect,
  useLayoutEffect,
  useRef,
  useState,
} from "react";
import {
  LayoutDashboard,
  Logs,
  Settings,
  X,
  Download,
  Maximize2,
  Minimize2,
} from "lucide-react";
import { t, locale } from "./i18n";
import { isDesktop } from "./platform";
import { connector, notify, startConnector } from "./state/connector";
import { startAgents } from "./state/agents";
import { startAgentActivity, startSubscriptions } from "./state/subscriptions";
import { startTasks, tasks } from "./state/tasks";
import {
  startUpdateChecks,
  updates,
  checkUpdate,
  showUpdate,
  updateVisible,
  installDirect,
} from "./state/updates";
import { navigation, type Page } from "./state/navigation";
import { panelPreferences } from "./usage-rail/preferences";
import type { PanelPreferences } from "./usage-rail/layout";
import { panelLayers, panelHandoff, panelAnchorAt } from "./state/panels";
import {
  capturePanelOrigin, takePanelOrigin, animateOriginContent, surfaceOf,
  morphEasing, reducedMotion, type PanelOrigin,
} from "./components/panelMorph";
import { displayMessage } from "./messages";
import ConnectionOverview from "./components/ConnectionOverview";
import TasksPage from "./components/TasksPage";
import RecordsPage from "./components/RecordsPage";
import { AppUpdateDialogs } from "./components/AppUpdate";
import AgentDisplaySettings from "./components/AgentDisplaySettings";
import TrayPanel from "./tray-panel/TrayPanel";
import { Dialog, Icon, IconButton, Loading, Notice, HoverScope } from "./components/ui";
const SettingsPage = lazy(() => import("./components/SettingsPage"));
const BrowserRailPreview = import.meta.env.DEV
  ? lazy(() => import("./usage-rail/BrowserRailPreview"))
  : null;
export default function App() {
  locale.use();
  const { feedback } = connector.use(),
    taskState = tasks.use(),
    nav = navigation.use();
  updates.use();
  const [page, setPage] = useState<Page>("overview"),
    [usage, setUsage] = useState(false);
  const [sheetWide, setSheetWide] = useState(false);
  const sheet = useRef<HTMLElement>(null),
    lastPage = useRef<Page>("tasks"),
    sheetOrigin = useRef<PanelOrigin | undefined>(undefined),
    sheetVisualCleanup = useRef<(() => void) | undefined>(undefined),
    sheetMotion = useRef<Animation | null>(null),
    sheetClosing = useRef(false),
    backdropDown = useRef(false);
  const layers = panelLayers.use();
  useLayoutEffect(() => {
    if (page === "overview" || !sheet.current) return;
    const node = sheet.current,
      rect = node.getBoundingClientRect(),
      source =
        ((panelHandoff.until ?? 0) > performance.now()
          ? panelHandoff.from
          : undefined) ??
        sheetOrigin.current?.rect ??
        document.querySelector(".navigation-surface")?.getBoundingClientRect();
    const handedOff = (panelHandoff.until ?? 0) > performance.now() && !!panelHandoff.from;
    panelHandoff.from = undefined;
    if (source && !reducedMotion()) {
      const visual = handedOff ? undefined : sheetOrigin.current;
      sheetMotion.current = node.animate(
        [
          {
            transform: `translate(${source.x - rect.x}px,${source.y - rect.y}px)`,
            width: `${source.width}px`, height: `${source.height}px`, opacity: 1,
            ...(visual?.surface ?? {}),
          },
          { transform: "none", width: `${rect.width}px`, height: `${rect.height}px`, opacity: 1, ...surfaceOf(node) },
        ],
        { duration: 480, easing: morphEasing },
      );
      const contentAnimations = Array.from(node.children).map((child) => child.animate(
        [{ opacity: 0 }, { opacity: 1 }], { duration: 280, delay: 130, fill: "backwards" },
      ));
      const cleanup = sheetVisuals(rect, false, !handedOff);
      sheetVisualCleanup.current = () => { cleanup(); contentAnimations.forEach((a) => a.cancel()); };
      void sheetMotion.current.finished.then(cleanup, cleanup);
    }
    document.querySelector<HTMLElement>(".capsule-title")?.focus();
    return () => { sheetMotion.current?.cancel(); sheetVisualCleanup.current?.(); };
  }, [page]);

  function sheetVisuals(rect: DOMRect, closing: boolean, showOrigin = true) {
    const visual = showOrigin ? sheetOrigin.current : undefined;
    const nodes = Array.from(document.querySelectorAll<HTMLElement>(".navigation-capsule, .navigation-surface"));
    const opacities = nodes.map((el) => el.style.opacity);
    const transitions = nodes.map((el) => el.style.transition);
    nodes.forEach((el) => { el.style.opacity = "0"; el.style.transition = "none"; });
    const clear = visual ? animateOriginContent(visual, rect, 480, 51, closing) : () => {};
    let done = false;
    return () => {
      if (done) return;
      done = true;
      clear();
      nodes.forEach((el, i) => {
        // Settle the capsule's new layout before enabling its CSS transitions.
        void el.offsetHeight;
        el.style.opacity = opacities[i];
        el.style.transition = transitions[i];
      });
    };
  }

  async function closeSheet(replacement?: HTMLElement) {
    const node = sheet.current;
    if (!node || sheetClosing.current) return;
    sheetClosing.current = true;
    if (
      node &&
      !matchMedia("(prefers-reduced-motion: reduce)").matches &&
      !replacement
    ) {
      const rect = node.getBoundingClientRect();
      const dock = document.querySelector(".navigation-surface")!.getBoundingClientRect();
      const visual = sheetOrigin.current;
      if (visual) {
        visual.rect = new DOMRect(dock.x, dock.bottom - visual.rect.height, visual.rect.width, visual.rect.height);
      }
      const to = visual?.rect ?? dock;
      const current = { transform: getComputedStyle(node).transform, width: `${rect.width}px`, height: `${rect.height}px`, ...surfaceOf(node) };
      sheetMotion.current?.cancel();
      sheetVisualCleanup.current?.();
      const natural = node.getBoundingClientRect();
      sheetMotion.current = node.animate(
        [
          current,
          {
            transform: `translate(${to.x - natural.x}px,${to.y - natural.y}px)`,
            width: `${to.width}px`, height: `${to.height}px`,
            ...(visual?.surface ?? {}),
          },
        ],
        { duration: 480, easing: morphEasing, fill: "forwards" },
      );
      const cleanup = sheetVisuals(rect, true);
      const contentAnimations = Array.from(node.children).map((child) => child.animate(
        [{ opacity: getComputedStyle(child).opacity }, { opacity: 0 }],
        { duration: 180, fill: "forwards" },
      ));
      sheetVisualCleanup.current = () => { cleanup(); contentAnimations.forEach((a) => a.cancel()); };
      await sheetMotion.current.finished.catch(() => {});
    }

    if (replacement && node) {
      panelHandoff.from = node.getBoundingClientRect();
      panelHandoff.until = performance.now() + 100;
      panelHandoff.trigger = replacement;
    }
    sheetClosing.current = false;
    setPage("overview");
    requestAnimationFrame(() => {
      const target =
        replacement ??
        document.querySelector<HTMLElement>(
          `[data-page="${lastPage.current}"]`,
        );
      target?.focus({ preventScroll: true });
      if (replacement) replacement.click();
    });
  }

  function navigate(next: Page) {
    if (next !== "overview") {
      sheetOrigin.current = takePanelOrigin();
      lastPage.current = next;
      setSheetWide(false);
    }
    setPage(next);
  }
  useEffect(() => {
    const stops = [
      startConnector(),
      startSubscriptions(),
      startAgentActivity(),
      startAgents(),
      startTasks(),
      startUpdateChecks(),
    ];
    return () => stops.forEach((stop) => stop());
  }, []);
  useEffect(() => {
    if (!isDesktop) return;
    let stopped = false;
    const stops: (() => void)[] = [];
    void import("@tauri-apps/api/event").then(async ({ listen }) => {
      const listeners = await Promise.all([
        listen("updates:check", () => {
          showUpdate();
          void checkUpdate();
        }),
        listen<string>("navigate", (e) => {
          if (["overview", "settings", "logs", "tasks"].includes(e.payload))
            navigate(e.payload as Page);
        }),
        listen<PanelPreferences>("usage-panel:preferences", (e) =>
          panelPreferences.set(e.payload),
        ),
        listen("agents:settings", () =>
          navigation.set((old) => ({ ...old, agentSettings: true })),
        ),
        listen<string>("subscriptions:open", (e) => {
          navigation.set((old) => ({ ...old, providerId: e.payload }));
          navigate("overview");
        }),
        listen<string>("connection-error", (e) => notify(e.payload, true)),
      ]);
      if (stopped) listeners.forEach((stop) => stop());
      else stops.push(...listeners);
    });
    return () => {
      stopped = true;
      stops.forEach((stop) => stop());
    };
  }, []);
  const pending = taskState.records.filter(
    (r) => r.state === "awaiting-approval",
  ).length;
  const pages = [
    { id: "tasks" as const, label: t("tasks"), icon: LayoutDashboard },
    { id: "logs" as const, label: t("records"), icon: Logs },
    { id: "settings" as const, label: t("settings"), icon: Settings },
  ];
  return (
    <div
      className={`app-scene ${sheetWide ? "sheet-wide" : ""} ${isDesktop ? "desktop" : ""} ${isDesktop && navigator.platform.toLowerCase().includes("mac") ? "mac" : ""}`}
      onClickCapture={(e) => capturePanelOrigin(e.target)}
      onKeyDown={(e) => {
        if (
          e.key === "Escape" &&
          !e.defaultPrevented &&
          page !== "overview" &&
          !layers.length
        ) {
          e.preventDefault();
          void closeSheet();
        }
        if (e.key === "Tab" && page !== "overview" && !layers.length) {
          const nodes = Array.from(
            document.querySelectorAll<HTMLElement>(
              '.page-sheet button:not(:disabled),.page-sheet input:not(:disabled),.page-sheet [tabindex="0"],.navigation-capsule .capsule-close',
            ),
          ).filter((n) => n.getClientRects().length && !n.closest("[inert]"));
          const index = nodes.indexOf(document.activeElement as HTMLElement);
          if (
            (e.shiftKey && index <= 0) ||
            (!e.shiftKey && index === nodes.length - 1)
          ) {
            e.preventDefault();
            (e.shiftKey ? nodes.at(-1) : nodes[0])?.focus();
          }
        }
      }}
    >
      {isDesktop && (
        <div className="window-drag-strip" data-tauri-drag-region />
      )}
      <main
        className="home-workspace"
        inert={page !== "overview" || layers.length > 0}
      >
        <ConnectionOverview onUsage={() => setUsage(true)} />
      </main>
      {page !== "overview" && (
        <div
          className="sheet-backdrop"
          onPointerDown={(e) =>
            (backdropDown.current =
              e.button === 0 && e.target === e.currentTarget)
          }
          onPointerCancel={() => (backdropDown.current = false)}
          onClick={(e) => {
            if (
              backdropDown.current &&
              e.target === e.currentTarget &&
              !layers.length
            )
              void closeSheet(panelAnchorAt(e.clientX, e.clientY));
            backdropDown.current = false;
          }}
        />
      )}
      <div
        className={`navigation-surface ${page !== "overview" ? "expanded" : ""} ${updateVisible() ? "has-update" : ""}`}
        aria-hidden="true"
      />
      {page !== "overview" && (
        <section
          ref={sheet}
          className="page-sheet"
          data-panel-depth="1"
          data-recessed={layers.length > 0 || undefined}
          inert={layers.length > 0}
          aria-label={pages.find((item) => item.id === page)?.label}
        >
          <div className="page-sheet-content">
            <main
              className={`workspace ${page === "logs" ? "records-workspace" : ""}`}
            >
              {page === "tasks" ? (
                <TasksPage />
              ) : page === "logs" ? (
                <RecordsPage />
              ) : (
                <Suspense fallback={<Loading />}>
                  <SettingsPage />
                </Suspense>
              )}
            </main>
            <footer className="sheet-footer">
              <IconButton
                className="capsule-close"
                icon={X}
                label={t("backToHome")}
                onClick={() => void closeSheet()}
              />
              <h1 className="capsule-title" tabIndex={-1}>
                {pages.find((item) => item.id === page)?.label}
              </h1>
              <IconButton
                className="panel-width-toggle"
                icon={sheetWide ? Minimize2 : Maximize2}
                label={t(sheetWide ? "restorePanelWidth" : "expandPanelWidth")}
                aria-pressed={sheetWide}
                onClick={() => setSheetWide(!sheetWide)}
              />
            </footer>
          </div>
        </section>
      )}
      <nav
        className={`navigation-capsule ${page !== "overview" ? "expanded" : ""} ${updateVisible() ? "has-update" : ""}`}
        inert={page !== "overview" || layers.length > 0}
        aria-hidden={page !== "overview"}
        aria-label={t("mainNavigation")}
      >
        <HoverScope
          activeKey={page !== "overview" || layers.length > 0 ? "" : undefined}
          className="capsule-icons"
          inert={page !== "overview"}
          aria-hidden={page !== "overview"}
        >
          {updateVisible() && (
            <IconButton
              className="update-shortcut"
              icon={Download}
              label={t("viewUpdate")}
              onClick={() => void installDirect()}
            />
          )}{" "}
          {pages.map((item) => (
            <button
              key={item.id}
              data-panel-anchor
              data-page={item.id}
              data-hover-target={item.id}
              aria-label={item.label}
              title={item.label}
              onClick={() => navigate(item.id)}
            >
              <Icon icon={item.icon} size={20} />
              {item.id === "tasks" && pending > 0 && (
                <span className="task-count">{pending}</span>
              )}
            </button>
          ))}
        </HoverScope>
      </nav>
      {feedback.text && (
        <div className="app-feedback">
          <Notice
            tone={feedback.error ? "danger" : "success"}
            action={
              <IconButton
                icon={X}
                label={t("dismissMessage")}
                onClick={() => notify("")}
              />
            }
          >
            {displayMessage(feedback.text)}
          </Notice>
        </div>
      )}
      <AppUpdateDialogs />
      {nav.agentSettings && (
        <AgentDisplaySettings
          onClose={() =>
            navigation.set((old) => ({ ...old, agentSettings: false }))
          }
        />
      )}
      {usage && (
        <Dialog
          onClose={() => setUsage(false)}
          title={t("trayUsage")}
          headerless
          width={386}
        >
          <TrayPanel
            embedded
            onNavigate={(next) => {
              setUsage(false);
              navigate(next);
            }}
          />
        </Dialog>
      )}
      {BrowserRailPreview && !isDesktop && page === "overview" && (
        <Suspense fallback={null}>
          <div inert={layers.length > 0}>
            <BrowserRailPreview />
          </div>
        </Suspense>
      )}
    </div>
  );
}
